### ISSUE TITLE
Update makefile to catch WSL folder error

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#1103]
This continues from https://github.com/openmaptiles/openmaptiles/issues/1095#issuecomment-819679870

Windows Subsystem for Linux not read correctly `*.bbox` file and raise an error.

How to update Makefile to catch this error?

**Comment by zstadler** [comment]
The Makefile can identify this configuration by running `df --output=fstype /tileset` in an `openmaptiles-tools` container. The reported filesystem type should not be `9p`.

I suggest this check is integrated into the `define assert_area_is_given` hook because this hook is already executed by the relevant make targets.

One possible way for this integration is:
```
ifeq ($(shell $(DOCKER_COMPOSE) 2>/dev/null run --rm openmaptiles-tools df --output=fstype /tileset),Type 9p)
  define assert_area_is_given
	@echo ""
	@echo "ERROR: Windows native filesystem"
	@echo ""
	@echo "Please avoid running OpenMapTiles in a Windows filesystem."
	@echo "See https://github.com/openmaptiles/openmaptiles/issues/1095#issuecomment-817095465"
	@exit 1
  endef
else
  ifeq ($(strip $(area)),)
    define assert_area_is_given
	@echo ""
	@echo "ERROR: $(AREA_ERROR)"
	@echo ""
	@echo "  make $@ area=<area-id>"
	@echo ""
	@echo "To download an area, use   make download <area-id>"
	@echo "To list downloadable areas, use   make list-geofabrik   and/or   make list-bbbike"
	@exit 1
    endef
  else
    ifneq ($(strip $(AREA_INFO)),)
      define assert_area_is_given
	@echo "$(AREA_INFO)"
      endef
    endif
  endif
endif
```

Note: The existing code for `define assert_area_is_given` is used when the filesystem is not an issue.

**Comment by zstadler** [comment]
@TomPohys, what do you think?

**Comment by TomPohys** [comment]
Looks very good, thank you for this! Could you please create a PR?

**Comment by zstadler** [comment]
Will do.

Please note that https://github.com/openmaptiles/openmaptiles/blob/76d5d753d8fae35e4d316f5532461835a3acf36b/Makefile#L164-L181 is dead code. It's functionality is now done in https://github.com/openmaptiles/openmaptiles/blob/76d5d753d8fae35e4d316f5532461835a3acf36b/Makefile#L79-L128

The PR will also clean this.
