### ISSUE TITLE
Unnamed bridges disrupt transportation_name continuity

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1131]
Blocks #1128

I discovered this while working on #1128 and felt that it deserves its own discussion and a separate PR focusing just on this bugfix.

Highway shield rendering depends on highway continuity over long stretches.  Adjacent segments of highway with the same network, ref, etc, get coalesced together using an `ST_LineMerge()` function in postgres.  That way, at lower zooms, you still have one continuous segment of highway that the style can use to place shield markers.

However, road continuity is disrupted by bridges or tunnels (`brunnel`, in the schema).  This means that any highway with a non-trivial number of bridges, including tiny unnamed bridges, will cause OMT to chop up the road at each transition between bridge and regular roadway.  Thus at lower zooms, these road segments between bridges quickly become small and suppress `transportation_name` layer labelling.

Example section of I-80 with an unnamed bridge:
![image](https://user-images.githubusercontent.com/3254090/123790979-ebfaf880-d8ac-11eb-8825-917540a710c7.png)

Adjacent section without a bridge:
![image](https://user-images.githubusercontent.com/3254090/123791057-01702280-d8ad-11eb-8bb7-1f52f35ce10b.png)

I propose the following behavior:
- The `brunnel` key will only be set when it has different attributes (such as `name`) from the adjacent stretches of highway.  Unnamed bridges/tunnels should be coalesced into adjacent highway stretches.

This will ensure that distinctly named bridge/tunnel objects will still expose a `brunnel` key.  For example, we would still like to separately label the [Ted Williams Tunnel](https://www.openstreetmap.org/way/290277568) as "Ted Williams Tunnel" rather than "Massachusetts Turnpike"

This behavior can be accomplished by creating a custom aggregation function for bridges/tunnels during the construction of the `transportation_name_linestring` table

**Comment by TomPohys** [comment]
Great catch! The PR is very welcome. Thanks!

**Comment by zstadler** [comment]
Doing spatial analysis, such as "it has different attributes (such as name) from the adjacent stretches of highway" is a complex task.

A different implementation approach is to include two types of objects in the `transportation_name` layer:
1. Merged sections of highway with identical name, ref, network, etc, ignoring their `brunnel` field
2. Merged sections of highway with identical name, ref, network, etc, and identical non-empty `brunnel` value

The style file would show both. Moreover, style authors create separate style layers for the two and give higher priority to names of non-empty `brunnel` highway sections.

**Comment by ZeLonewolf** [comment]
Investigating this further, we also have the issue of _named_ bridges disrupting route connectivity.  Thus, I would propose a slightly different breakdown:
1. Merged sections of highway with identical `class`, `network` and `ref`, ignoring `brunnel` and `name*` values
2. Merged sections of highway with identical `class` and identical non-empty `name` values, ignoring `network` and `ref`; and setting the `brunnel` value _only_ if all segments in the merged section have the same `brunnel` value.

The first object allows for shield rendering.
The second type of object allows for name rendering.

The "all segments in the merged section" logic can be accomplished with a postgres aggregate function.

**Comment by zstadler** [comment]
@ZeLonewolf,

Can you elaborate about the issue with named bridges?

Also,
> 2. Merged sections of highway with identical class and identical non-empty name values, ignoring network and ref; and setting the brunnel value only if all segments in the merged section have the same brunnel value.

is not very SQL-friendly. Perhaps you could define it as separate grouping with and without a `brunnel` values.

**Comment by ZeLonewolf** [comment]
The situation I envision is something like this: 

![image](https://user-images.githubusercontent.com/3254090/124321313-7bbdd280-db4b-11eb-9450-c053b8c301ee.png)

This should decompose into four objects.  First, you want one feature that represents the continuous route network.  Next, you want a feature for each continuous section of named road (i.e. the "City Expressway") on either side of the named bridge.  Lastly, you want a feature for the named bridge ("City Bridge"):

![image](https://user-images.githubusercontent.com/3254090/124321371-9132fc80-db4b-11eb-9d3e-ab064e7768f6.png)

The problem you have, is that the unnamed bridges are still tagged with the name "City Expressway", so you need a way to differentiate them from the named bridges.  Hence I propose an aggregate function to differentiate between sections of named highway that have bridges from named bridges.

**Comment by zstadler** [comment]
As far as I understand the example you gave, my proposal will provide the following merged segments

![image](https://user-images.githubusercontent.com/1304610/124323204-957e0a80-db89-11eb-9fd9-afc4933c4718.png)

The top line of the above diagram, that also ignores the `name*` tags, is unrelated to bridges.

![image](https://user-images.githubusercontent.com/1304610/124322707-9b272080-db88-11eb-85ef-94e7b64e074c.png)

Nevertheless, it can be added as a 3rd merge operation.

#### Moving forward
The `transportation_name` layer currently groups ways with identical values of the following fields:

https://github.com/openmaptiles/openmaptiles/blob/1b0b1fd12131167904b61628c1ea403359f4a6e7/layers/transportation_name/update_transportation_name.sql#L90

where `tags` includes the `name*` fields.

In order to proceed with a clear definition of the required outcome, I suggest you create a table that defines the proposed new merges.

For example, this table represents my initial proposal

| # | Merge when these fields are identical | using ways where |
|---|---|---|
| 1 | `name`, `name_en`, `name_de`, `tags`, `ref`, `highway`, `subclass`, `level`, `layer`, `indoor`, `network_type` | `brunnel` is empty |
| 2 | `name`, `name_en`, `name_de`, `tags`, `ref`, `highway`, `subclass`, `level`, `layer`, `indoor`, `network_type`, `brunnel` | `brunnel` is non-empty |

**Comment by ZeLonewolf** [comment]
The issue I am grappling with (and needs to be clarified before describing the merge in table format as noted), is that this approach would _also_ produce two additional unwanted objects, in cases where a bridge carries a named road.  I've added these additionally in red:

![image](https://user-images.githubusercontent.com/3254090/124327914-aa8d7600-db56-11eb-90a5-daa678167d76.png)

If we are willing to accept those additional bridge features, then this is a pretty easy problem and your initial proposal satisfies this.  However, if we wish to exclude them, it seems like additional aggregation logic is required.

**Comment by ZeLonewolf** [comment]
I believe the correct merge should be as follows:

\# | Merge when these fields are identical | using ways where
-- | -- | --
1 | `highway`, `subclass`, `network_type`, `ref` | `network_type` and `ref` are non-empty
2 | `name*`, `tags`, `ref`, `highway`, `subclass`, `level`, `layer`, `indoor`, `network_type` | `name` is non-empty

Additionally, for the second merge, the value of `brunnel` is aggregated such that the value is `MAX(brunnel)` where `MAX(brunnel)=MIN(brunnel)`, otherwise `NULL`

I've been testing this merge and it seems to be producing expected results.

Named tunnel:

![image](https://user-images.githubusercontent.com/3254090/124360725-39eb6580-dbf9-11eb-8141-b5dce9253f4f.png)

**Comment by zstadler** [comment]
The second group seems to address the original intent of this issue by removing `brunnel` from the `GROUP BY` list if fields, yet preserving the `brunnel` value if all group members have identical values.

The first group seems to target a different goal: group by `ref` and `network_type`, ignoring the `name`. I assume this is intended for the rendering highway shields. Its selection criteria should allow empty `network_type` in order to make it useful outside of the US/GB/Canada.

I think the first group should have a layer of its own, potentially named `transportation_ref`, rather than including it in the `transportation_name` layer. Just think about creating documenting the combined layer and explaining why the `transportation_name` layer has objects with no `name` field...

**Comment by ZeLonewolf** [comment]
> I assume this is intended for the rendering highway shields.

Yes -- this is most certainly the intent (and that's why this issue is a spin-off of #1128).  However, the second group does still solve a legitimate problem of creating longer continuous stretches of same-named roads which should produce better labelling results.

Given this feedback -- I'm going to work on a PR to address the second group and open a new issue proposing to create a `transportation_ref` layer.

**Comment by TomPohys** [comment]
In Czech Republic (and many other places) there are `motorway` with no `name` but with just `ref.` Even the `ref` could be part of motorway name. 

Examples: 
 - https://www.openstreetmap.org/way/39815329#map=14/49.7650/14.9556
 - https://www.openstreetmap.org/way/39815331#map=17/49.77801/14.93540
 - https://www.openstreetmap.org/way/24889825#map=15/47.1127/8.3600

So dividing a `transportation_name` layer with tag `name` and `transportation_ref` with tag `ref` is not a good approach, because both (`name` and `ref`) relating with the name (not the tag `name`) of the road. 

There was also a bug (https://github.com/openmaptiles/openmaptiles/issues/762), when the roads was not stich together by `tags` and thanks to @zstadler who fixed it.

**Comment by ZeLonewolf** [comment]
Thanks @TomPohys for this detail, I'll need to study this issue more with regard to highway shields.

I think #1141 is still valid for the specific issue outlined here, which is a bridge disrupting continuity in the `transportation_name` layer, leading to suppression of highway text labelling.  That PR still preserves both `name` and `ref` inclusion in `transportation_name`, so it should be consistent with the principles you've outlined.

**Comment by TomPohys** [comment]
Thanks for that! I will merge it after the checks are finished.
