### ISSUE TITLE
Enable Travis Build

### ISSUE THREAD

**Issue by lukasmartinelli** [openmaptiles/openmaptiles#127]
I don't have admin rights for OpenMapTiles on Travis.
@klokan  Please enable the build for openmaptiles/openmaptiles.

**Comment by stirringhalo** [comment]
I also lost the ability to push changes from my remote git client, I would love to have that re-enabled.

**Comment by klokan** [comment]
Sorry. No restriction are intentional...

@lukasmartinelli you have full Admin/Owner rights on the organization now (on the switch I could choose only one person).

@stirringhalo on all repos you should have the same rights as before already. Switch did not make any change. What repo has the problem with push?

BTW openmaptiles/openmaptiles enabled on Travis.
https://travis-ci.org/profile/openmaptiles is public, right?

**Comment by stirringhalo** [comment]
@klokan Hmm, thanks for checking. I'll figure out if its something on my end!

**Comment by lukasmartinelli** [comment]
> @klokan Hmm, thanks for checking. I'll figure out if its something on my end!

I guess it is because applications require permission on organization level. I once received a GitKraken permission request on OSM2VT from you that I confirmed.

**Comment by stirringhalo** [comment]
@lukasmartinelli  Yep, that would've been it. I confirmed on one of my repos that pushes still work so I think it was an organizational change. Openmaptiles is no longer in my remotes. Should we diagnose through email?

**Comment by lukasmartinelli** [comment]
Travis build seems to be working! Thanks @ImreSamu for the `.travis.yml` file.
