### ISSUE TITLE
Add customary units to mountain_peak layer

### ISSUE THREAD

**Issue by daliborjanak** [openmaptiles/openmaptiles#1288]
Now it is not possible to display different units in maps for peak elevation. We would like to add tagging that will mark unit that is customary in the country. So basically tag peaks in the USA to make

Add tag **customary_units** with values “ft” or “m” to **mountain_peak** layer

**Comment by nnhubbard** [comment]
Why would this be needed when the math can be done when styling?

**Comment by ZeLonewolf** [comment]
@nnhubbard this is not about doing the math, since both `ele` (meters) and `ele_ft` (feet) are already present in the tiles.

Is there a real use case where somone would want to render feet in the US and meters elsewhere, on the same map?  I would normally expect consistent labelling, i.e. a US map user would want to see feet worldwide and vice-versa for a non-US map user.

I would also suggest only adding the `ft` where present and assume `m` by default to avoid unnecessary tile size inflation.

**Comment by nnhubbard** [comment]
> Is there a real use case where someone would want to render feet in the US and meters elsewhere, on the same map?

I don't see why anyone would ever want to do that.

**Comment by daliborjanak** [comment]
It is displayed like that for example in Google maps Look at the contours 
![image](https://user-images.githubusercontent.com/1891090/140036412-013cd424-86a7-49bc-965f-18e51704d9de.png)

We are making one global map that can be used by users from the US and also from Europe to see their native units when they look at their position. 

@ZeLonewolf thanks for the comment we think about that. So it would be better to use only "customary_ft" with values 1 or null and present it only in peaks in US. I don't want to remove ele_ft to have braking change
