### ISSUE TITLE
Faster transportation_names

### ISSUE THREAD

**Issue by stirringhalo** [openmaptiles/openmaptiles#129]
In light of https://github.com/openmaptiles/openmaptiles/issues/114 and how it takes 9 hours to rematerialize the transportation_names layer, I went looking for a solution to find an SQL nearly as good looking for much less time.

The work is in https://github.com/openmaptiles/openmaptiles/tree/faster_transportation_name, and initial results suggests massive speed improvements for the import-sql stage, but rendering is slowed (about half speed). I am investigating the rendering end now.

**Switzerland, (note the slow method is into a materialized view, the fast method is into a table, but the performance holds up)**
Slow method:
SELECT 235496
Time: 18775.231 ms

Fast method:
SELECT 119097
Time: 3055.946 ms

The SELECT count difference is due to the fact that the fast method ends up with ST_MultiLineString while the slow method ends up with ST_LineString. I can duplicate that behaviour in the fast method. That may also be a cause of the slow rendering.

It might be possible to get the fast method to handle planet updates in under one hour, I will compare with a larger import and see.

**Comment by stirringhalo** [comment]
For France (with work_mem set to 5GB):
Slow method: 119349.826 ms
Fast method: 6031.045 ms

So massive gains possible when it fits in memory. We really ought to tune the postgis install...

**Comment by stirringhalo** [comment]
@lukasmartinelli 
Question, how critical is transportation_name and can the layer simply be dropped? It feels silly to have nearly the same information, twice, and make adjusting the style based on label preference harder. Like for example, one cannot label railroads as those are not included in transportation_names.

I figure leave the layer out and let mapbox-gl-js sort labels on transportation out. Saves DB update time, tile size and rendering time. Adds slight complexity to the styles.

**Comment by lukasmartinelli** [comment]
> Question, how critical is transportation_name and can the layer simply be dropped? It feels silly to have nearly the same information, twice, and make adjusting the style based on label preference harder. Like for example, one cannot label railroads as those are not included in transportation_names.

The stitching together of the lines is necessary so we get the longest possible lines for roads with the same names. This in turn then helps Mapbox GL JS place the labels with regards to the padding/space between labels. Otherwise it happens that at every turn/crossing there are new linestrings and therefore each road is labelled individually.

..that's not always such a big deal. It really appears when trying to label highway refs - which will result in a forest of labels without stitched together motorways.

But actually OpenMapTiles is ready for such situations - for you to leave out transportation_name all you have to do is comment it out in the tileset `openmaptiles.yaml` file and you have your own tileset that is easier to keep up to date.

It's really cool you're pushing it to the edges. Never thought it would even be possible daily with all the preprocessing - but I don't think we'll ever have a need for more than weekly.

**Comment by stirringhalo** [comment]
> The stitching together of the lines is necessary so we get the longest possible lines for roads with the same names. This in turn then helps Mapbox GL JS place the labels with regards to the padding/space between labels. Otherwise it happens that at every turn/crossing there are new linestrings and therefore each road is labelled individually.

Have you tried some of the labelling options in the style spec? I haven't yet, but I will with just rendering the transportation layer. I suspect it should handle the conflict resolution just fine!

> But actually OpenMapTiles is ready for such situations - for you to leave out transportation_name all you have to do is comment it out in the tileset openmaptiles.yaml file and you have your own tileset that is easier to keep up to date.

That's what I love about OpenMapTiles, but where's the fun in that?!

**Comment by stirringhalo** [comment]
Closed with #133
