### ISSUE TITLE
Grey overlay over Berlin

### ISSUE THREAD

**Issue by hyperknot** [openmaptiles/openmaptiles#1331]
In the newest version / master, there is a slight grey overlay over Berlin (with OSM Bright). In the api.maptiler.com version, (which I guess is the latest stable release), this is not present. The style is the same.

![Swipe between maps 2021-12-23 14-38-12](https://user-images.githubusercontent.com/494223/147248298-39a795e6-67f9-4fc7-88c1-9d957077da60.jpg)

**Comment by hyperknot** [comment]
On higher zoom levels, there is also a grey overlay, might be the same or might be a different one. Only in Berlin (not in London, Budapest, Hamburg).
![Swipe between maps 2021-12-23 14-42-56](https://user-images.githubusercontent.com/494223/147249049-243ff351-19c6-45e4-85da-adf25a755a7f.jpg)

**Comment by TomPohys** [comment]
Hi, sorry for the delayed answer. This is caused by `place=suburb` in `landuse` layer. Please see - https://overpass-turbo.eu/s/1gnu
If you remove `suburb` from `landuse-residental` style layer, it will fix the grey overlay. 
![image](https://user-images.githubusercontent.com/5182210/155278246-2ef2f1d6-b930-4626-bc2d-32ff38abaf85.png)


Of course, you can style the `suburb` differently by adding a style layer e.g. `landuse-suburb` where the filter will be `class==suburb`

**Comment by hyperknot** [comment]
It actually behaves very strange, for low zoom levels it's nice and continuous, then it's broken like this under 11, then it's again good on 11+.

**Comment by hyperknot** [comment]
Anyway the original issue is solved, I just wanted to raise this strange behaviour of landuse.
