### ISSUE TITLE
labels in iraq not correct

### ISSUE THREAD

**Issue by bilemedimkq** [openmaptiles/openmaptiles#1398]
Hello.

I created a tile file using the command:

`./quickstart.sh iraq`,

then, I started a tile server with the command of `docker run -it -v $(pwd)/tiles:/data -p 8080:8080 maptiler/tileserver-gl iraq.mbtiles` and "tileserver-gl" and I realized that street names and even city names dont look correctly. 

However when I checked your sample maps, I saw they are correct on these maps I wonder what is the problem ?

If you like, I can share the .mbtiles file with you.

Your sample map;
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/42588052/170987864-4f36ad65-5734-4c00-b0c9-4f29e2b6054a.png">

My map:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/42588052/170987894-ee631025-d0e9-4715-8d88-f52336af6b28.png">

**Comment by Spiekerooger** [comment]
The problem is in your style file or by the fonts loaded. You'll need a font that is capable of displaying Arabic letters for all layers where names occur.

First check your network connections to see the http requests for fonts, if you don't see errors there, check for the fonts loaded and if one of them is capable of Arabic letters (e.g. Noto Sans Arabic Regular|Italic|Bold|Light).

If none of the loaded fonts is capable of Arabic letters, you'll have to a) add a font to all layers in the style capable of Arabic and b) have a font url that will get you the added font as part of the loaded font package.

**Comment by bilemedimkq** [comment]
Hi @Spiekerooger , thank you for your answer.

There is no problem in accessing the fonts, fonts are accessible. 

<img width="1717" alt="image" src="https://user-images.githubusercontent.com/42588052/171621565-6b222e2c-c91d-43b9-b329-ef5aac76b8f5.png">


but, I found something.
this is the tileserver-gl-styles project's fonts directory; 

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/42588052/171621619-3c470682-e23d-4979-a533-19e75a10940d.png">


I think the fonts that this project use is not compatible with Arabic language.

When I examined the fonts in tileserver-gl-styles, I saw that they use a different format called ".pbf ".
how can I create ".pbf" files from a font ?

**Comment by Spiekerooger** [comment]
Yes, you will need at least Noto Sans Arabic Regular, so you'll need a fontstack directory like (at least) "/Noto Sans Arabic Regular, Noto Sans Regular/" with all those files.

See https://github.com/openmaptiles/fonts about generating fontstacks.

**Comment by bilemedimkq** [comment]
@Spiekerooger  its worked, thanks
