### ISSUE TITLE
water__waterway.sql:992: ERROR:  column "source_ids" ... doesn't exist

### ISSUE THREAD

**Issue by Bonjour123** [openmaptiles/openmaptiles#1556]
When following [this tutorial ](https://www.linuxbabe.com/ubuntu/basemap-tileserver-gl-openmaptiles-ubuntu-22-04)to set up a tile server, when running make import-sql, I get the followig error:

  ```
psql:/sql/parallel/water__waterway.sql:955: NOTICE:  relation "osm_important_waterway_linestring_source_ids" already exists, skipping
  CREATE TABLE
  Time: 0.434 ms
  TRUNCATE TABLE
  Time: 19.769 ms
  TRUNCATE TABLE
  Time: 9.039 ms
  psql:/sql/parallel/water__waterway.sql:992: ERROR:  column "source_ids" of relation "osm_important_waterway_linestring" does not exist
  LINE 1: ...INTO osm_important_waterway_linestring (geometry, source_ids...

```

I understand the table creation statement is at:
https://github.com/openmaptiles/openmaptiles/blob/a548093e08dc1e82958f205ad49618d2b2efd17d/layers/waterway/update_important_waterway.sql#L23

and the faulty sql statement is at:

https://github.com/openmaptiles/openmaptiles/blob/a548093e08dc1e82958f205ad49618d2b2efd17d/layers/waterway/update_important_waterway.sql#L60

I think this is related to these 2 statements:

https://github.com/openmaptiles/openmaptiles/blob/a548093e08dc1e82958f205ad49618d2b2efd17d/layers/waterway/update_important_waterway.sql#L35

https://github.com/openmaptiles/openmaptiles/blob/a548093e08dc1e82958f205ad49618d2b2efd17d/layers/waterway/update_important_waterway.sql#L157

**Comment by Bonjour123** [comment]
Should I comment line 157 ?

**Comment by amistadpl** [comment]
I have the same problem. Import works only on clean database. Any idea?

**Comment by michalgwo** [comment]
I stumped upon the same problem, always when updating the database (on the second run of import-sql) one of these tables didn't have a `source_ids` column: `osm_important_waterway_linestring`, `osm_transportation_merge_linestring_gen_z8`, `osm_transportation_merge_linestring_gen_z11`, `osm_important_waterway_linestring`. One of my suspected culprits was the layer I'm using [route_bicycle_hiking](https://github.com/makina-maps/openmaptiles-contrib-bicycle_hiking_route/tree/master/route_bicycle_hiking) (which is from the external repository), but I didn't really test OpenMapTiles without this layer, because I found other "solutions" and I didn't really believe that this could cause problem in another layer. 

One way I was "handling" this at first, was by recreating the whole database:
```
make destroy-db
make stop-db
make clean-unnecessary-docker
make remove-docker-images
make refresh-docker-images
```

But it didn't really solve the problem, tiles were generated successfully for the first time, but I was unable to update them without recreating the database (which takes time).

The other, less annoying solution was to comment out these 4 lines of code:
https://github.com/openmaptiles/openmaptiles/blob/dfd20c647c1a20e45e5ac869d3769289db17979b/layers/transportation_name/update_transportation_name.sql#L393
https://github.com/openmaptiles/openmaptiles/blob/dfd20c647c1a20e45e5ac869d3769289db17979b/layers/transportation/update_transportation_merge.sql#L310
https://github.com/openmaptiles/openmaptiles/blob/dfd20c647c1a20e45e5ac869d3769289db17979b/layers/transportation/update_transportation_merge.sql#L635
https://github.com/openmaptiles/openmaptiles/blob/dfd20c647c1a20e45e5ac869d3769289db17979b/layers/waterway/update_important_waterway.sql#L157

It fixed the problem, but I have no idea what these lines are for, so I'm not certain if it doesn't break anything. If anyone reading this knows the code of OpenMapTiles, I would appreciate an explanation of what these lines are for, and whether is it safe to delete them or better to look somewhere else to fix this problem.

**Comment by Youssef-Harby** [comment]
@michalgwo the same issue here +1

**Comment by npignier-cegedim** [comment]
+1

**Comment by NasH5169** [comment]
+1
