### ISSUE TITLE
Docs about distributed workflow [Question]

### ISSUE THREAD

**Issue by sweco-semtne** [openmaptiles/openmaptiles#159]
Hi,
In the old osm2vectortiles docs there were instructions on how to setup rendering with multiple workers. 
Is this possible with the new openmaptiles workflow?

**Comment by klokan** [comment]
This part of the docs has not been ported.

The same principles apply for OpenMapTiles as did for OSM2VectorTiles, because the software stack is similar...

We have worked hard on an improved faster cluster setup which is now used in for the regular rendering of the official OpenMapTiles planet by @klokantech.

For an equivalent of paid six working hours, we can now render the world with custom layers or adjusted features for any interested party. If you are keen on production deploy of OpenMapTiles let us know at info@klokantech.com.

**Comment by sweco-semtne** [comment]
Thanks for your reply.
Should I interpret this as that the workflow for that won’t be ported since you are doing that commercially?
That´s fine. Just needed a clarification.
And keep up the good work!

Regards,
Mats

**Comment by klokan** [comment]
Related comment: https://github.com/openmaptiles/openmaptiles/issues/242#issuecomment-300398462
