### ISSUE TITLE
stiles not works

### ISSUE THREAD

**Issue by proton5000** [openmaptiles/openmaptiles#1681]
I started the tile server according to your instructions
https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md

```
git clone https://github.com/openmaptiles/openmaptiles.git
cd openmaptiles
./quickstart.sh ukraine
```

`make start-tileserver`

then going to http://localhost:8080 I see the maps, but they have a standard style
I decided to use the style https://github.com/openmaptiles/osm-bright-gl-style
I used your instructions https://github.com/openmaptiles/openmaptiles/blob/master/style/README.md
copied the style.json file to the style folder, then `make download-fonts` and `make build-style`

`make start-tileserver`

but the map style has not changed, it is still the same by default

tell me, please, how I can update the map style?

**Comment by TomPohys** [comment]
Hi, all the styles in OpenMapTiles organization (e.g. also https://github.com/openmaptiles/maptiler-basic-gl-style/tree/gh-pages or https://github.com/openmaptiles/fiord-color-gl-style/tree/gh-pages) have the branch `gh-pages` where the style and sprites are available. 

https://github.com/openmaptiles/osm-bright-gl-style/tree/gh-pages

You will probably have to adjust path for `sprites`, `glyphs` and `source tiles` (based on OMT style).

**Comment by nikolaydyankov** [comment]
@TomPohys I believe he was asking how to add an additional style to the tileserver, so that it shows in http://localhost:8080

![image](https://github.com/user-attachments/assets/558b9e87-1138-4899-a9b8-f76c8c69ed4b)

I still can't figure it out. In the README.md it says:

> You can start from several GL styles supporting the OpenMapTiles vector schema.

You click [MapTiler Basic](https://github.com/openmaptiles/maptiler-basic-gl-style) and you are taken to a repo with a style.json and no instructions how to use it. You check the /style dir in the main repo and it contains config.json and style-header.json. 

Where should I put the style?

I run `make build-style` and it generates `build/style/style.json`. How do I add an additional style? I replace the contents of this dir with https://github.com/openmaptiles/maptiler-basic-gl-style, restart the tileserver but nothing has changed.

Either I'm missing something obvious, or the docs could use some love :)

**Comment by nikolaydyankov** [comment]
Figured it out:

1. Add the style to style/config.json:

```
{
  "options": {
    "paths": {
      "fonts": "/data/fonts",
      "sprites": "/build/style",
      "styles": "/build/style"
    }
  },
  "styles": {
    "OSM OpenMapTiles": {
      "style": "style.json",
      "tilejson": {
        "type": "overlay"
      }
    },
    "Basic GL": {
      "style": "style-basic-gl.json",
      "tilejson": {
        "type": "overlay"
      }
    }
  },
  "data": {
    "openmaptiles": {
      "mbtiles": "/data/tiles.mbtiles"
    }
  }
}
```

2. Download the style.json file from https://github.com/openmaptiles/maptiler-basic-gl-style
3. Rename it to style-basic-gl.json
4. Move it to build/style/style-basic-gl.json

**Comment by TomPohys** [comment]
Thanks for posting the solution! 

Please, if you have further questions, feel free to reopen the issue or create a new issue.
