### ISSUE TITLE
status implemantation schema

### ISSUE THREAD

**Issue by Lorzer** [openmaptiles/openmaptiles#169]
@klokan Maybe I missed the information, but I am not sure if I understand this right and I hope you can answer me this question: The schema https://openmaptiles.org/schema/ isn't completely implemented yet, right? For example missing are aeroways/runways as linestrings or the possibility to distinguish railways into lightrails, tram etc. as shown in https://openmaptiles.org/schema/#transportation. Or are these just missing in the data coming from https://free.tilehosting.com/data/v3.json, where I tried to find them in Maputnik/Inspect Mode.

**Comment by klokan** [comment]
The https://openmaptiles.org/schema/ documents the status of the code in this repository.

We have not long ago finished rendering of world for v3.4 release - https://github.com/openmaptiles/openmaptiles/releases/tag/v3.4 - this is now available on free.tilehosting.com, but not in the downloads yet (where is now v3.3). We work hard now on testing the updating process.

The aeroways/runways as linestrings has an open request at #141 

If you have another request for what is missing and should be added - please create a ticket where we can discuss the implementation ideas and let us know if you start to work on this.

Our priorities are set by what our customers need, but this a community open-source project with external contributors (for example @ImreSamu and @stirringhalo) so if you have a diferent needs and priority then KlokanTech you can push your ideas forward! We welcome if other people use this open-source code, render their own tiles and integrate it with their products. That's why the project has been released as open-source. It would be great if people contribute back and help us to improve the schema. Your pull requests are very welcome ;-).

**Comment by Lorzer** [comment]
Thanks for the feedback. My problem though was solved by switchting to another style in Maputnik; the Klokan basic style is just not showing e.g. subways; I thought, that the inspect mode shows the "raw" schema, but is obviously depending on the choosen map style.

**Comment by klokan** [comment]
Please make a ticket on maputnik. Inspect/x-ray mode should present all the available data IMHO.

**Comment by jirik** [comment]
Runways added in https://github.com/openmaptiles/openmaptiles/pull/192
