### ISSUE TITLE
Runways and coastlines?

### ISSUE THREAD

**Issue by weatherc** [openmaptiles/openmaptiles#181]
I have successfully did some small moddifications to my data, like at what zoomlevel are what lake-data used. Must say its much easier to moddificate now than with old osm2vectortiles :)

Have 2 questions tought:
1. How to get airport runways showing up?
2. How to get coastline? Fill-outline works for ne_10m_lakes but not for osm-data as its in blocks. 

I have used OSM Bright as base for my custom style.

**Comment by klokan** [comment]
Great to hear it is now easier for you to modify the data structure of this project!

- Runways as lines - requested already under #141
- Coastline is with blocks because we use OSM data water polygons shapefiles http://openstreetmapdata.com/data/water-polygons - stitching would be required either in postprocessing (on the final produced PBF tiles) or just before passing the relevant bounds into mapnik for generating the vector tile. It is not easy to do - you can workaround it with style partly - with outline only at certain zoom levels.

In all cases a pull request is welcome - we would be happy to review your code and merge it into this open-source project.

If you are willing to instead cover the costs of related development in the team on our side, we can offer our assistance via prepaid support: https://openmaptiles.com/support/

**Comment by tinoue** [comment]
OSM bright has no styles for aeroway layer. You should add your own style to show runway (aerodrome, taxiway etc..).
