### ISSUE TITLE
Water layer is over-simplified at zoom level 8

### ISSUE THREAD

**Issue by tinoue** [openmaptiles/openmaptiles#205]
https://openmaptiles.github.io/osm-bright-gl-style/#8.01/43.2660/145.5424

See coastline and road around "Nemuro Peninsula.".
Water layer is relatively over simplified at this zoom level and the Road #44 seems to run over ocean.
Also, It seems to be OK to simplify "landcover class=wood" more.

**Comment by tinoue** [comment]
Or is this geometry mismatch between Natural Earth and OSM ?
North-West coastline seems to unmatch with roads.
https://openmaptiles.github.io/osm-bright-gl-style/#7.01/43.279/141.155

**Comment by klokan** [comment]
Thanks for the report. It is indeed the switch between Natural Earth and OSM which makes the trouble on this zoom level.

It would be good to simplify the OSM water polygons (from "import-water") via SQL in Postgres and use them one level up instead of NE.

See:
https://github.com/openmaptiles/openmaptiles/tree/master/layers/water

Could you please try to do this and make a pull request? It may be a great contribution to the OpenMapTiles open-source project and a lovely first code from a new project team member ;-)

Once you have the first version we can review your code and merge it, if it fine for production use in the next official release! It would be cool @tinoue

**Comment by stirringhalo** [comment]
Here's some proposed changes:
https://github.com/openmaptiles/import-water/pull/1
https://github.com/openmaptiles/openmaptiles/pull/207

Needs testing, but it's a start.

**Comment by jirik** [comment]
@stirringhalo Thanks, I will look at it next week.

**Comment by stirringhalo** [comment]
Closed in https://github.com/openmaptiles/openmaptiles/pull/207
