### ISSUE TITLE
POIs at zoom 14 cut on tile edges on raster tiles

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#224]
Raster rendering of OSM Bright in highly populated places esp. on zoom level 15 - such as in New York or in London shows clipped labels for POIs:

<img width="670" alt="screen shot 2017-04-19 at 15 41 18" src="https://cloud.githubusercontent.com/assets/59284/25183138/feffbb1c-2516-11e7-89a4-d7b24d993c6c.png">

For example:
#15/40.7889/-73.9556
#15/51.5252/-0.1065

We may need to increase the buffer of this layer probably - if it does not significantly affect the size of tiles on zoom 14.

A workaround is to adjust the styles appropriately (avoid rendering on edges of tiles with [symbol-avoid-edges](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-symbol-avoid-edges) of the POI layer or display the POIs first on a deeper zoom level).

Improving POI ranking (importance of POIs) in the style and vector tiles may also help.

**Comment by klokan** [comment]
@stirringhalo - is this something you would be willing to have a look at?

**Comment by stirringhalo** [comment]
@klokan  Won't have time for this one.

**Comment by klokan** [comment]
OK. Thanks, @stirringhalo.

I am +1 for a fast fix using `symbol-avoid-edges` in GL style now.

**Comment by lincomatic** [comment]
FYI, assuming the proper place to up the buffer is the buffer_size parameter in poi.yaml, increasing the buffer up all the way up to 512 doesn't fix the issue. This is using osm-bright theme:

![image](https://cloud.githubusercontent.com/assets/1422186/25465863/d75ba1f4-2ab9-11e7-8dd7-e65a019593c4.png)

**Comment by klokan** [comment]
@lincomatic - could you please try the `symbol-avoid-edges` parameter on the layer in GL style? This will fix the problem even without changing the buffers in vector tiles - it is change only on the GL JSON style.

**Comment by klokan** [comment]
Still to be tested on raster tiles of different styles.

**Comment by muesliq** [comment]
We tried increasing buffer sizes in our vector tiles but that didn't help. We believe it's a Mapbox GL Native bug. Test setup here: https://github.com/mapbox/mapbox-gl-native/issues/11838 

(If you agree it would help to voice your support there.)

**Comment by lincomatic** [comment]
> @lincomatic - could you please try the symbol-avoid-edges parameter on the layer in GL style? This will fix the problem even without changing the buffers in vector tiles - it is change only on the GL JSON style.

Sorry, I forgot to report back. symbol-avoid-edges helps, but doesn't fix the bug. It just shows up less often. It is definitely a bug in mapbox-gl-native

**Comment by chebourne** [comment]
I am getting the raster tile rendering bug described here.
 
I’m a bit confused as to where things are with this bug:
 
Are you still awaiting a bug fix to Mapbox GL library?
 
Is the only workaround to use the symbol-avoid-edges option in the style?
 
It looks like that option has not been applied to the standard OpenMapTiles osm-bright style – is there a reason for that?
 
Where exactly do I have to apply that option – like this?:
 
{
  "id": "poi-level-1",
  "type": "symbol",
  "source": "openmaptiles",
  "source-layer": "poi",
  "minzoom": 14,
  _"symbol-avoid-edges": true,_
  "filter": [
    "all",
    [
      "==",
      "$type",
      "Point"
    ],
    [
      "<=",
……
 
On each POI level?

**Comment by chebourne** [comment]
Thanks, will do. 

Any idea regarding the symbol-avoid-edges workaround?

**Comment by muesliq** [comment]
That's a layout property:

`"layout": {"symbol-avoid-edges": true}`

**Comment by chebourne** [comment]
Yes, that worked - many thanks. But as people have said not ideal.

I then realised I had not checked the affected layers buffer size - setting the parameter -b256 when creating mbtiles from json with tippecanoe also solved this problem with better results. Although increased my layer size from 6MB to 32MB!

**Comment by Scsilbaugh** [comment]
I am still seeing this issue with city names.  Some city names work, but others do not. I have set symbol-avoid-edges to true for all labels and that did not seem to change anything.  In the below screenshot, Towson, Randallstown, Baltimore, Timonium, and Cockeysville are all cut off.

![city_names](https://user-images.githubusercontent.com/47194525/52015343-c08f3c00-24af-11e9-9ea8-00925f187670.PNG)

I have seen mention of increasing layer buffer size, but I have not been able to find any information on how to do that.  Could someone point me to documentation on how to set that?  Are there any other things I could try to fix this issue?

**Comment by chebourne** [comment]
@Scsilbaugh - is this using your own layer or are you editing a base style?

**Comment by Scsilbaugh** [comment]
That screenshot is with a style I created trying to get Mapbox's Light style to work with Tileserver-gl.  However, I used the Positron style as well and the same thing happened.

**Comment by Scsilbaugh** [comment]
@chebourne Here is a screenshot of the same(ish) area with the Positron style.  Notice Baltimore, Timonium, Cockeysville, and others are cut off.

![positron_tiles](https://user-images.githubusercontent.com/47194525/52135277-6d35fe80-2613-11e9-8b98-d738155f7ce1.png)

**Comment by klokan** [comment]
https://www.maptiler.com/maps/#positron//raster/9.34/-76.4833/39.3133

**Comment by Scsilbaugh** [comment]
@klokan Yes, I have seen that too, which is why I know it isn't a problem with the style. So, my question is why is it happening on my instance?  I installed tileserver-gl via source and I am using a planet.mbtiles file I bought from OpenMapTiles (as recommended by tileserver docs).  I already said that I used the Positron style.  What else is there that I can check?  I tried using the symbol-avoid-edges property on the Mapbox Light style I converted(first image) but that did not seem to work.

**Comment by klokan** [comment]
In MapTiler Cloud we use the same data you get commercially at  https://openmaptiles.com/downloads/planet/
If you use the same style you should get the same result.

**Comment by Scsilbaugh** [comment]
Okay, that is the planet file I am using as well. Any ideas on what I can do to debug this issue?

**Comment by chebourne** [comment]
@klokan Petr, your answer to @Scsilbaugh  is rather disingenuous.

There is definitely still a problem with labels being cut at tile edges and not just at zoom level 14.

For example: [https://www.maptiler.com/maps/#streets//raster/15/-0.12763/51.51891](url)
Notice cutting off of "Tottenham Court Road" and other items in a vertical line on the tile edge.

And the same here: [https://www.maptiler.com/maps/#bright//raster/15/-0.1326/51.51957](url)
and at zoom 14: [https://www.maptiler.com/maps/#bright//raster/14/-0.1287/51.52212](url)

It seems to be a problem when symbol layers are used in the style e.g. place names, points of interest.

I have always had problems with this on raster tiles, buffer sizing and using "symbol-avoid-edges" makes no difference, vector tiles are fine.

We have converted most apps over to use vector tiles but there are still occasions where raster tiles are useful to have so it would be good to have this resolved.

The Mapbox-GL native bug mentioned above: [https://github.com/mapbox/mapbox-gl-native/issues/11838](url), seems to suggest that this problem was fixed in V4. And you confirmed to me separately that Tileserver-GL is currently using V4 so is there any idea as to why this problem is persisting?

**Comment by Scsilbaugh** [comment]
Is there any news on what is causing these issues?  Sounds like the problem isn't just with my setup or style if others(including maptiler) are displaying this issue.

**Comment by chebourne** [comment]
@Scsilbaugh 
I have been in communication with Mapbox for the last week regarding this problem and I now have a definitive response.

The short answer is that this is a problem with Mapbox GL rendering raster tiles and that it will not be resolved - even though they say they support raster tiles it is clear they do not (or only on legacy products).

This is a summary of our communication:

> I believe this is occurring because the tiles are being converted and served as raster tiles instead of vector. This is a known issue that has been addressed inMapbox GL JS with vector tiles. Mapbox.js is a deprecated library, and Mapbox GL JS is our most up to date library that is regularly maintained for bugs & replenished with new features. I highly recommend using Mapbox GL JS. Check out the same location with vector tiles.

My response: 
> So you’re saying that Mapbox raster maps do not work correctly in Mapbox-JS, Mapbox-GL or any other library – you will always get problems with labels at tile edges?
 
Surely this is a problem with the Mapbox-GL server library that renders the raster tiles on your servers? Is it ever going to be fixed in there?

And their reply:
> Text is handled through collision boxes on the tiles, which is addressed in the Mapbox GL JS library. The fix for avoiding tile boundaries has been addressed in our current suite of products. Mapbox.js is a deprecated project, and we can't guarantee that everything is going to work as well as it does with Mapbox GL JS. Mapbox.js isn't routinely monitored for bugs or replenished with new features, for these reasons I highly recommend using Mapbox GL JS. If you have any questions about converting from Mapbox.js to Mapbox GL JS, I'm here to help you forward.

And when I asked for some clarification:
> Mapbox GL JS isn't optimized to run raster tiles. 

We don't offer an out of the box way to serve map styles as raster tiles using Mapbox GL JS. The fix for text labels has been addressed in Mapbox GL for vector tiles, check out this issue for some information: 
https://github.com/mapbox/mapbox-gl-js/issues/2706.

Overall, I recommend using Mapbox GL JS and vector tiles.

So there you have it. Unless something is forked, OpenMapTiles and Tileserver-GL rely on Mapbox GL library and therefore you will always get this problem happening.

The only solution is to use vector tiles instead.

**Comment by sfkeller** [comment]
Hi all; just chiming in. @chebourne reported

> The short answer is that this is a problem with Mapbox GL rendering raster tiles and that it will not be resolved - even though they say they support raster tiles it is clear they do not (or only on legacy products) and nobdy, up until now, has been prepared to admit it.
...
> The only solution is to use vector tiles instead.

If this is true, then I'm speechless about Mapbox!

**Comment by pathmapper** [comment]
Tileserver GL uses Mapbox GL Native for server side rendering, so this is a bug in GL Native, right?

There is still an open issue: https://github.com/mapbox/mapbox-gl-native/issues/8587

Looks like they are waiting for an example which shows the bug.

**Comment by pathmapper** [comment]
Interesting comment here: https://github.com/mapbox/mapbox-gl-native/issues/12763#issuecomment-434025498

> Are you using `mode: "tile"`? If not, it defaults to "static" mode, which won't avoid edges (static mode is made for making an entire map in a single render call).

Is Tileserver GL using `mode: "tile"`? Only had a [quick look](https://github.com/klokantech/tileserver-gl/search?q=mode&unscoped_q=mode) ...

**Comment by rzoller** [comment]
> Is Tileserver GL using `mode: "tile"`? Only had a [quick look](https://github.com/klokantech/tileserver-gl/search?q=mode&unscoped_q=mode) ...

I doubt it, I think this should be done [here](https://github.com/klokantech/tileserver-gl/blob/63483a3155e34a146964db32c667f76098066584/src/serve_rendered.js#L147-L241), if the example in https://github.com/mapbox/mapbox-gl-native/issues/12763#issuecomment-434025498 is correct.

I also couldn't find any documentation for `mode: "tile"`, but this issue explains some changes and fixes around it: https://github.com/mapbox/mapbox-gl-native/issues/12461

**Comment by pathmapper** [comment]
Tried it out: https://github.com/pathmapper/tileserver-gl/commit/3f2bc211e8512208f301fba9a3997a2e1ab23226

So far it looks good:

Before: 
![bildschirmfoto von 2019-02-14 12-37-25](https://user-images.githubusercontent.com/20856381/52784827-a8462200-3056-11e9-98a8-cb6d6a704434.png)

With `mode: "tile"`:

![bildschirmfoto von 2019-02-14 12-36-21](https://user-images.githubusercontent.com/20856381/52784851-b7c56b00-3056-11e9-85fe-6cdd7c9b3c53.png)

**Comment by chebourne** [comment]
@pathmapper 
Better, but there are still problems at other places:
![london](https://user-images.githubusercontent.com/20801744/52785948-518a1980-3051-11e9-9fbf-765bf21572a7.png)

**Comment by pathmapper** [comment]
@chebourne yeah right.

`v1.8` of the style is not using  `"symbol-avoid-edges": true`.

Here is a test where it is added to all symbol layers:

![auswahl_529](https://user-images.githubusercontent.com/20856381/52787197-666caa00-305d-11e9-8fc1-757e612ffc69.png)

Anyone is able to spot cut labels?

**Comment by Scsilbaugh** [comment]
![52787197-666caa00-305d-11e9-8fc1-757e612ffc69](https://user-images.githubusercontent.com/47194525/52790892-acae1300-3035-11e9-8bdb-a3dd2870570e.png)


I outlined the labels I found that are cut off in red.  The ones in orange I wasn't sure if they were wrong or not.

**Comment by RicoElectrico** [comment]
My question is: so what does Mapbox use themselves? 
If you make a style in Mapbox Studio that uses vector tiles, they have an API endpoint for raster tiles as well. And they work fine, no label clipping occurs.
WTF is going on?

**Comment by lincomatic** [comment]
Anyone using their raster API will get the clipping. Check Strava. They have the clipping bugs. Mapbox’s themes tend to hide them better, but eventually, you’ll see the clipping, under the right conditions.

**Comment by klokan** [comment]
TileServer GL V3 branch has the `mode:tile` included - which improves `symbol-avoid-edges` solution - but it is not perfect. https://github.com/maptiler/tileserver-gl/issues/344

There is also "tileMargin" config option which may kill the performance of TileServer GL, but really solves the problem here for those who need it solved desperately. https://github.com/maptiler/tileserver-gl/pull/379

There is not much more what can be done on the OpenMapTiles project side for this issue.
