### ISSUE TITLE
Tutorial for generating planet tiles?

### ISSUE THREAD

**Issue by zflamig** [openmaptiles/openmaptiles#242]
There doesn't seem to be a single tutorial for how to generate the planet mbtile files, but it would be great if there was. I see scattered documentation about using RabbitMQ and a cluster to do this...

**Comment by sfkeller** [comment]
http://fuzzytolerance.info/blog/2017/04/25/Generating-your-own-OpenMapTiles/ ?

**Comment by stirringhalo** [comment]
There's a new, upcoming option, see https://github.com/openmaptiles/openmaptiles/pull/240 . In summary, generate-vectortiles will not be needed, you could go straight from import to hosting tiles. No Mbtiles will be generated, which may be an issue if you need those for something else.

This will likely change as the underlying PostGIS methods are changed, but a similar process will work.

**Comment by klokan** [comment]
A team of people puts a huge amount of effort into this project for years now - and we are keen to continue and keep everything as open as possible - and improve the schema and open-source tools further - with the help of the user community and the third party developers who kindly contribute to the code of this project.

The rendering of a planet on a cluster is one of the things we offer commercially to sustain and improve the OpenMapTiles project code base and its infrastructure (free CDN and the free download section).

If you need the MBTiles for the whole planet with the latest OpenMapTiles schema for your business, please consider a purchase of the Production package (https://openmaptiles.com/production-package/) and you get the up-to-date MBTiles data for your unlimited production use - with regular weekly updates, and also global contour lines and hillshades tiles as extras - for price very probably cheaper than the costs of generating these on your own hardware with your team of programmers.

We offer the OpenMapTiles planet data also downloadable for free for non-commercial use - and an update of the free download section is already scheduled...

If you need adjusted vector tiles with extra data specific to your project or business you can:
- contribute with a Pull Request to the community maintained open-source official vector tile schema and your changes will be part of the future public OpenMapTiles releases and maintained
- render only the features you need into a separate MBTiles files with new layers - and combine our standard planet with your own extra layers - this is doable easily with JSON GL style and software stack powered by mapnik or tippecanoe. BTW the extra layers can be also generated on demand directly from the PostGIS by a third party tileservers (GeoServer, Tegola, etc.) and combined into a single map with TileServer GL - and served via composed vector tiles or raster tiles.
- or, if you really want to, set up your own cluster to generate the complete planet on regular basis on your own infrastructure with the help of available documentation and open-source components. If you need help with the setup we offer it privately at https://openmaptiles.com/support/

Feel free to study the existing documentation and source code and setup your own cluster yourself and completely independently of us otherwise, but please consider the real costs including working hours and compare it with our Production package offer.

The decission valid for now is to not publish our cluster setup documentation and the code yet, but offer the know-how as part of consulting and products. The future may bring changes on this decission...

Ideas for alternative sustainability plans are welcome - active maintenance and continuous developer effort is important for a healthy life of any open-source project...

BTW people should also consider Mapbox.com hosting offering, if attractive for them, as a lot of hard work on the open-source components and open standards used by OpenMapTiles project has been (and continues to be) developed by Mapbox engineers and is kindly released under an open-source license by the company. 

This ticket is duplicate to #159. Closing.

**Comment by lukasmartinelli** [comment]
> Feel free to study the existing documentation and source code and setup your own cluster yourself and completely independently of us otherwise, but please consider the real costs including working hours and compare it with our Production package offer.

To branch off of this @zflamig @sweco-semtne.
We also found that with OSM2VT we were the only ones who actually were using our OSS cluster code. No one else was using the distributed rendering. If someone creates distributed infrastructure it is often times very tightly coupled to the platform that team uses (AWS, Google cloud, Azure, Bare Metal) and their preferred tools (which kind of queue, AWS SQS, Beanstalk, RabbitMQ).
So if someone wants to build a distributed system of rendering tiles companies will usually roll their own.

Also this video https://www.youtube.com/watch?v=D7mmXonFIqA&feature=youtu.be gives a general overview of distributed rendering. As does the thesis https://github.com/osm2vectortiles/bachelor-thesis

**Comment by indus** [comment]
https://openmaptiles.com/docs/

**Comment by gka** [comment]
Btw, we would gladly purchase a production package, but your new terms of service make it completely impossible for us to work with you. Proxying and caching the tiles through our own infrastructure is an absolute must-have as we need to guarantee that the maps are still working 5 years from now. This is why we couldn't use MapBox and now it's why we can't use MapTiler.

Will post a tutorial once we figured out how to generate the planet tiles more efficiently (takes ~37 days using `quickstart.sh` currently).

**Comment by jirik** [comment]
@gka If you are interested in hosting data from openmaptiles.com on your own infrastructure, then these terms apply to you: https://openmaptiles.com/terms/ You don't need to use MapTiler Cloud hosting.

**Comment by qlerebours** [comment]
@gka when you say it takes approximatively 37 days, do you mean for zoom 0 - 14 ?
At this point I was able to generate tiles for zoom 0 - 13 in about 20 days but each zoom level will take much more time (it's almost exponential). To go to zoom 16, it would need about 700 days...
I'm just running this with a brand new SSD (1To), 16Gb RAM v4 cpu
Do you know if added more RAM and CPU should speed up the process ?

**Comment by nnhubbard** [comment]
Just a note. You should never generate tiles for anything past z14.

**Comment by qlerebours** [comment]
z14 = zoom 14 ? Why ?

**Comment by nnhubbard** [comment]
> z14 = zoom 14 ? Why ?

Over zoom will happen after zoom 14 (z14) and you will not get better data by building tiles for higher zoom levels. z14 over zoom can go up to z22 without any issues and still a high level of detail since they are vector tiles.

**Comment by qlerebours** [comment]
Is there something to implement for over zooming ? I'm using mapbox library with my generated tiles for zoom 0 - 7 and as soon as I zoom over zoom 7.99999, I have white tiles because openlayer tries to load zoom 8 (and search for files in my 8th folder)
Thanks for your answer :)

**Comment by nnhubbard** [comment]
> Is there something to implement for over zooming ? I'm using mapbox library with my generated tiles for zoom 0 - 7 and as soon as I zoom over zoom 7.99999, I have white tiles because openlayer tries to load zoom 8 (and search for files in my 8th folder)
> Thanks for your answer :)

This all depends on your SDK that is being used to view the `.mbtiles` file. I use the Mapbox SDK for iOS which handles over zooming.
