### ISSUE TITLE
place=suburb multipolygons missing

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#268]
e.g. this  and other similar suburb names/points/polygons seems to be completely missing from the 3.5 vector tiles: http://www.openstreetmap.org/relation/4572236

**Comment by jirik** [comment]
We are importing only point places now, but some of them are polygons (relations). About 6 % of all suburbs are polygons: https://taginfo.openstreetmap.org/tags/place=suburb#overview

**Comment by mmesbah** [comment]
Hello jirik, and thank you for your answer.

By "only point" polygons, you mean "node" rather than way/relations elements. right? If this is the case, please let me know in which parts of the code (imposm3, ...) or mapping yml files (openmaptiles) this is being done. In other words, what parts do we need to edit to involve way elements with place=neighbourhood on the import phase?

Thank you in advance.

**Comment by daliborjanak** [comment]
We will add this as a polygon to landuse as a class residential to fil "holes" in cities.
