### ISSUE TITLE
Show track/path sooner

### ISSUE THREAD

**Issue by Duke74** [openmaptiles/openmaptiles#271]
When using openmaptiles for hiking focused mapping, paths and tracks are displayed too late.

Making it difficult for the final user to find paths that are going around a mountain for example.

Paths and Tracks are currently displayed at zoom level : 14
Here is what it looks like (path and tracks are red):
![chrome_2017-05-31_15-59-25](https://cloud.githubusercontent.com/assets/1609064/26636262/7d105464-461c-11e7-8125-e62498cfae71.png)

In my opinion for the hiking map usecase it would be interesting to make it appear sooner (z11-12 ?):
It would allow us to make maps that looks like this:

![chrome_2017-05-31_15-59-06](https://cloud.githubusercontent.com/assets/1609064/26636368/db332418-461c-11e7-819e-cd9827cee9ee.png)
This map allow a bigger field of view making it easier to plan an hiking tour without having to scroll everywhere at zoom 14.
do you guys have the same opinion ?

To go arround the issue I'm generating my own vector tiles with the paths and tracks only and use it as an additional source in my style, it's working but it would be interesting to add this change to openmaptiles.

I noticed the issue for track and path but it may also apply to alpine_huts, viewpoints ...

**Comment by carlos-mg89** [comment]
Totally agree with this request. Would there be any way of changing any configuration so this is something that could be fixed? The paths and tracks are simply not in the MBTiles of zoom level less than 14. So it's not an issue of my style (I've checked with other MBTiles), and I'm modifying it for other elements.

**Comment by nnhubbard** [comment]
You are missing one thing. In `transportation/mapping.yaml` you would need to add `track` and `path` to the `sql_filter`, e.g.:

`sql_filter: highway IN ('motorway', 'trunk', 'primary', 'secondary', 'tertiary', 'motorway_link', 'trunk_link', 'primary_link', 'secondary_link', 'tertiary_link', 'track', 'path') AND NOT is_area AND ST_IsValid(geometry)`

**Comment by carlos-mg89** [comment]
I've just applied the changes to those 2 files, and just fired `./quickstart.sh area_to_be_downloaded`. Would this be enough? Or anything else has to be done for the layers to be taken into account?

**Comment by nnhubbard** [comment]
Yes it will be enough to include the data in the import. I don’t think the style need to be adjusted either,  but I can’t remember, not looking at my style sheet at the moment.

**Comment by carlos-mg89** [comment]
It worked like a charm! Thanks @nnhubbard 

Would you be interested that I send a PR with the changes?

**Comment by nnhubbard** [comment]
Sure, however I am not sure all users would want to start seeing trails at `z11`. In our app I give the option to turn this off and alternately see them starting at `z14` if the user wants.

**Comment by daliborjanak** [comment]
Ok, we would like to try that. Can you please make a pull request? Display it on Zooms >= 12. We will see if this not increase tile size too much

**Comment by carlos-mg89** [comment]
The code seems to have changed (I forgot to send my PR) and I'm not sure anymore I should even send it now. Since some things were added concretely in the lines that I removed.

If you want to try, just edit the files that are mentioned above and do leave as said up there. However, as I said, some changes were applied to those lines, and now they don't look exactly the same.

**Comment by jnucc86** [comment]
+1 on this, would be good to build in a variable function in settings to change min_zoom levels for certain layers.  Ill be having a go at the above in my build but obviously would be better to have it in the master.

**Comment by ZeLonewolf** [comment]
This is related to #1169, which proposes to show more important hiking routes at lower zooms.

**Comment by farfromrefug** [comment]
@ZeLonewolf i am not 100% sure but i dont think it is related to your PR. This issue is about showing path/track at lower level. Yours adds new "route" data for hiking. The data which is talked about here is already there just filtered to be shown at lower level.

**Comment by ZeLonewolf** [comment]
@farfromrefug it wouldn't solve this issue, but it is certainly _related_.  The purpose of my PR is to provide a way to show a filtered subset of the trail network at lower zoom.  This is the same thing that's done with roads today - motorways and trunks shown at a certain zoom, then primary at a higher zoom, then secondary at a yet higher zoom, and so forth.

With the path network, there's no real way to make a distinction between more important paths and less important paths.  You need that for low-zoom views because at some point showing everything is too cluttered.  By adding the route relations, it increases the ability of general purpose renderers to show some trails at lower zooms.  Another thought I had was that we could suppress unnamed, unmarked, or private trails at certain zooms.  If we just dump every path into lower zoom tiles, we would be burdening the tiles with insignificant paths that belong only at higher zooms.

In four years, nobody has solved this issue, but I propose that if we can look at the attributes of paths we can come up with smart way to come up with sub-sets of the path network that make sense to pull up to lower zoom, and membership in route relations ought to be something we consider.

**Comment by farfromrefug** [comment]
@ZeLonewolf i must disagree i am sorry. The issue here only talks about zoom 11/12 which as explained in the comments can be easily solved. I have done just that in my fork as i am sure a lot of people did.
You PR takes a different approach and adds new data and a new representation of the track/paths (no sac_scale, ref...) for ALL zoom levels. I know i have it too in my fork.
It is in my opinion a different beast

**Comment by ZeLonewolf** [comment]
Feel free to offer a PR so all can benefit...

**Comment by farfromrefug** [comment]
@ZeLonewolf of course i can the question is what zoom do we choose for the "official" openmaptiles repo? It has size consequences so we should trade carefully. I personally only do zoom 12.

**Comment by ZeLonewolf** [comment]
If that's the zoom that makes sense to the folks working on hiking-themed maps, then it seems reasonable to me.

**Comment by farfromrefug** [comment]
@ZeLonewolf ok i could do that. Could we maybe instead already think of a solution like @jnucc86 suggests? is there any way today to read it from an env variable?

**Comment by carlos-mg89** [comment]
I'm on board with z12 too. That's the one I'd use with my hiking app.

El dj., 19 d’ag. 2021, 14:02, farfromrefuge ***@***.***> va
escriure:

**Comment by farfromrefug** [comment]
@carlos-mg89 @ZeLonewolf is it necessary to add transportation name too at zoom 12? I personally did not add it. Not sure it is necessary

**Comment by ZeLonewolf** [comment]
@farfromrefug with regard to:
> build in a variable function in settings to change min_zoom levels for certain layers

I agree that this is needed, but it seems like a separate issue.  Do you know if there is already an open ticket for customizing zooms via configurations?  I have a few thoughts on how we can make this happen.  I'm specifically interested in filtering out buildings at lower zooms but the solution should be generic to any layer.

**Comment by farfromrefug** [comment]
@ZeLonewolf i dont think there is  and to be honest i really dont see how to do it :P 
i ll create the PR without transportation name for this issue

**Comment by ZeLonewolf** [comment]
We haven't gotten down to path rendering yet in openstreetmap-americana so I'm not sure whether or not it's needed at that zoom for my use case.  I agree with moving ahead with what would make sense for your use cases and if other consumers come up with a need for it, it's not problem to make future changes to add it.
