### ISSUE TITLE
"tags" column is actually a "names" column

### ISSUE THREAD

**Issue by nlehuby** [openmaptiles/openmaptiles#334]
In many layers, it seems that :
* the psql `tags` column is first set with all OSM tags
* then, some sql function transform this column in a hstore that only contains names for internationalisation purposes

for instance, for the waterway layer :
* https://github.com/openmaptiles/openmaptiles/blob/master/layers/waterway/mapping.yaml#L38
* https://github.com/openmaptiles/openmaptiles/blob/master/layers/waterway/name.sql

Why don't we create *another* hstore column for the names ?
If we can't do that (performance issue for instance), it could be great to rename the column from `tags` to `names` to ease the understanding

**Comment by jirik** [comment]
@nlehuby Yes, it's like you described it.

> Why don't we create another hstore column for the names ?

Another column mean to duplicate a lot of data. We want to have extra tags (names at this moment) in one place.

By the way, the reason why we are loading all tags and then deleting some of them is [historical](https://github.com/openmaptiles/openmaptiles/issues/266). It will be probably simplified in near future, so that we load only tags we really need.


> it could be great to rename the column from tags to names to ease the understanding

Now, there are only names. But it's not meant only for names. Other tags are coming, e.g. wikipedia URL and wikidata ID for 3.7 release.

**Comment by nlehuby** [comment]
Ok, thanks for your answer.

Why don't we keep all the tags in the postgres database, and then select the needed ones in the sql query that defines the layer (`my_layer_name.yaml`) ?

With the current architecture, we have to import again the whole OSM data if we want to add some new tags in the layer schema :(

**Comment by jirik** [comment]
> Why don't we keep all the tags in the postgres database, and then select the needed ones in the sql query that defines the layer (my_layer_name.yaml) ?

I guess because of performance and DB size (since I am not involved in the project from the beginning).

> With the current architecture, we have to import again the whole OSM data if we want to add some new tags in the layer schema :(

That's true. You can change the schema to import tags for all tables quite easily (e.g. into `tags` column). But importing all tags by default is a big change and I can't imagine we would accept such change without really good reason and testing.

On the other hand it would be nice to have **option** for development to import all tags for all tables. If you are willing to make PR for such optional tags loading, we can discuss it in more detail.

**Comment by nlehuby** [comment]
I guess this is an option in openmaptiles-tools, in both `generate-imposm3` and `generate-sql`, right ?

**Comment by jirik** [comment]
> I guess this is an option in openmaptiles-tools, in both generate-imposm3 and generate-sql, right ?

Yes, exactly. It would be perfect first to resolve #266 and then to implement this issue. I would like to look at #266 in next two weeks (together with other changes heading to 3.7). Then you can start with this one.

**Comment by nlehuby** [comment]
Hi !

any update on this ?

**Comment by jirik** [comment]
Yes! #266 was closed on November 10.

Current state (3.7) is that
- we are not loading all `tags`, only subset (`load_all: true` was removed)
- we are not slicing language tags, so all loaded tags remain in DB (the only exception is `osm_important_waterway_linestring`)

If you want to optionally load all tags, please create PR for openmaptiles-tools. Optional argument of `generate-imposm3` should be enough.

**Comment by nlehuby** [comment]
I don't think this is still relevant, now that all loaded tags remain in the database.
