### ISSUE TITLE
Indonesia and Philippines names missing

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#342]
Names for **Indonesia** and **Philippines** come very "late" if zoomed in - they are missing completely on lower zoom tiles (0-4 zoom), appear on zoom 5 but even there with very low rank (6). Even East Timor has higher ranking. As result everyone will get map without names of the 2 largest and most populous countries in the region (your sample map style):

![screenshot 2017-11-06 14 35 42](https://user-images.githubusercontent.com/5609650/32441346-d51bf1bc-c2ff-11e7-8371-8860d52ae0b8.png)

**Comment by makella** [comment]
hello some additional comments on this issue:

- first, it looks like there are actually **no country labels that are in `rank 4 or 5`** so you basically jump from `3 to 6` with nothing in between 
  - I assumed that rank was `1-6` as noted in their schema documentation:
"The rank field for countries and states ranges from 1 to 6" 

- second, since there are no labels introduced in these ranks, the next (and highest level) is `6`. 
  - as you can imagine, labels for countries like Indonesia, Philippines, Singapore, Denmark, etc. that should be in lower ranks will be labeled differently than places that should probably be in higher ranks.  
  - In `rank 6`, we have everything like small island labels as well. As a consequence, there will not be the proper hierarchy of label sizes. 
  - For example, adding the labels requested, you will see that a place like East Timor (that has a `rank of 3`) will be a lot larger than the label for Indonesia, Singapore, etc -- is this "correct"?:
![screen shot 2017-11-13 at 9 55 12 am](https://user-images.githubusercontent.com/1566273/32742538-97ff9c52-c85e-11e7-8466-52dc0896acec.png)
  - this is because for other places that have `rank=6` can't and should not be labeled with the same hierarchy as lower rank countries:
![screen shot 2017-11-13 at 10 38 14 am](https://user-images.githubusercontent.com/1566273/32742610-d3015be2-c85e-11e7-9157-40975a06cb4d.png)

- third, without a better distribution of ranking, we will run into unintended consequences like this label cluster at z6:
![screen shot 2017-11-13 at 10 23 21 am](https://user-images.githubusercontent.com/1566273/32742901-a0b32728-c85f-11e7-8744-d56861f70f3a.png)

cc @jaakla

**Comment by makella** [comment]
Another one I noticed that is in `rank=6` is Denmark. Not sure if there are others as well...

**Comment by jirik** [comment]
@jaakla @makella 
The initial issue of missing names is fixed (tested on Philippines and Denmark).

@makella Could you please move the first additional comment to separate issue? I guess at least something from your second comment is fixed by 30539e7. The third comment is related to #224 and you should be able to improve it in GL style using [`symbol-avoid-edges`](https://github.com/openmaptiles/openmaptiles/issues/224#issuecomment-296215152).

**Comment by jirik** [comment]
@makella I've reflected the first comment in https://github.com/openmaptiles/openmaptiles/commit/2097b2c31b16167faf358d48bb35a23c68e28285

rank | number of countries before the change | number of countries after the change
--- | --- | ---
1 | 36 | 36
2 | 88 | 88
3 | 57 | 59
4 | 3 | 15
5 | 2 | 33
6 | 69 | 24

**Comment by makella** [comment]
@jirik thank you for looking into this for us! 

which part of the issue should i move?

in regards to #3, this is the raster styling with CartoCSS. We have been able to remove some of the cut off labels with a combination of `text-wrap-width`, and other properties through zoom. I don't want to use `text-avoid-edges` on country or city labels as it really reduces the amount of labels and one label that shows at one zoom might not at the other. 

i'm not sure if there is a buffer in the vector tiles (?)

in general, any additional information on this would be extremely helpful.

**Comment by jirik** [comment]
@makella As I already implemented the first part, I think there is no need to create new issues. I hope https://github.com/openmaptiles/openmaptiles/commit/30539e78d193d9a471aaea5581372b3d0702a524 and 2097b2c addresses key parts of what you've described.

The buffer is specified per layer. For place layer it is currently 256 (the highest among all layers).
