### ISSUE TITLE
tm2 style error

### ISSUE THREAD

**Issue by webmap2015** [openmaptiles/openmaptiles#355]
I created tiles.mbtiles successfully.

![image](https://user-images.githubusercontent.com/10267317/32701272-708c508c-c7e3-11e7-8642-4755a4e23703.png)

But, with https://github.com/mapbox/mapbox-studio-osm-bright.tm2.git

I can't see country, city, street labels.

Thanks.

**Comment by klokan** [comment]
OpenMapTiles has a different tile schema (internal data representation) from Mapbox.
You have to modify the styles (either .tm2 or GL JSON) as they are not compatible directly.

The osm-bright.tm2 has been ported from Mapbox schema to OpenMapTiles already at https://github.com/openmaptiles/mapbox-studio-osm-bright.tm2

BTW We recommend using new GL JSON style instead of old TM2 styles.

If you need raster tiles - just install OpenMapTiles Server and you get the .png tiles for OpenStreetMap in a few minutes from your laptop or server - with the OSM Bright style or any other OpenMapTiles style: https://openmaptiles.com/server/

**Comment by webmap2015** [comment]
Thank you.

**Comment by webmap2015** [comment]
Hi @klokan,

I want to port an existing TM2 style to OpenMapTiles by myself.

There is only one video at https://openmaptiles.org/docs/style/mapbox-studio-classic/.

Is there any much more tutorial?

Thanks.
