### ISSUE TITLE
Identify culvert in waterway layer

### ISSUE THREAD

**Issue by nlehuby** [openmaptiles/openmaptiles#360]
For now, there is no way to apply a custom style to a culvert part of a river.
In OSM, they are tagged with [tunnel=culvert](http://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dculvert)
This could be a class in the waterway layer to allow adequate tunnel styling.

Here is an example of culvert, in the middle of Paris : http://www.openstreetmap.org/way/338196702#map=15/48.8316/2.3556

In all OpenMapTiles opensource styles, it is displayed as a normal river, with buildings and roads on top of it which is very confusing.

![screenshot-2017-11-13 open map styles](https://user-images.githubusercontent.com/919962/32729368-bd605a3e-c883-11e7-99bd-50d62e69dfae.png)

**Comment by frodrigo** [comment]
#326

**Comment by jirik** [comment]
The original #326 is already merged in #393. So we can easily distinguish [`tunnel=yes`](https://wiki.openstreetmap.org/wiki/Key:tunnel).

However, we are probably not able to distinguish [`tunnel=culvert`](https://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dculvert) that is quite [frequent](https://taginfo.openstreetmap.org/keys/tunnel#values) (more than 40% of tunnels), because [culverts are probably converted to `FALSE`](https://imposm.org/docs/imposm3/latest/mapping.html#bool). This needs another improvements:
- to [import tunnel as string instead of boolean](https://github.com/openmaptiles/openmaptiles/blob/89ee0de23bf9582d5f1f127ed85488f6975d6383/layers/waterway/mapping.yaml#L21) (and rename it from is_tunnel to tunnel)
- to change [`waterway_brunnel` function](https://github.com/openmaptiles/openmaptiles/blob/89ee0de23bf9582d5f1f127ed85488f6975d6383/layers/waterway/waterway.sql#L4) to handle strings (should return `TRUE` for `'yes'` and `'culvert'`).

**Comment by jirik** [comment]
I meant not to distinguish tunnel=yes from tunnel=culvert in generated schema. I suggested only to map both tunnel=yes and tunnel=culvert to brunnel=tunnel (currently we map only tunnel=yes to brunnel=tunnel).

**Comment by frodrigo** [comment]
I have a simplest implementation:

```diff
diff --git a/layers/waterway/mapping.yaml b/layers/waterway/mapping.yaml
index c5f980d..9cebc85 100644
--- a/layers/waterway/mapping.yaml
+++ b/layers/waterway/mapping.yaml
@@ -19,6 +19,9 @@ tunnel_field: &tunnel
   key: tunnel
   name: is_tunnel
   type: bool
+  mapping:
+    true: [true, yes, 1, culvert, covered]
+    false: [__any__]
 bridge_field: &bridge
   key: bridge
   name: is_bridge
```

The highway brunnel should also be fixed.

**Comment by jirik** [comment]
Interesting, I did not know you can use `mapping` in this way in imposm3. Is it documented somewhere?

Anyway, if it works, PR is welcome

**Comment by jirik** [comment]
[Imposm3 doc](https://imposm.org/docs/imposm3/latest/mapping.html#bool):
> `bool`
> Convert true, yes and 1 values to true, otherwise use false.

However [the source code says something else](https://github.com/omniscale/imposm3/blob/20ad581d9bc3e17a198d881f571b644eff0235f3/mapping/columns.go#L64:L69):
```go
func Bool(val string, elem *element.OSMElem, geom *geom.Geometry, match Match) interface{} {
	if val == "" || val == "0" || val == "false" || val == "no" {
		return false
	}
	return true
}
```

So I tried to render the culvert in Paris. And it's already marked as tunnel:

![image](https://user-images.githubusercontent.com/2271850/35049805-6d40d532-fba1-11e7-9ca3-4f5e3d96dd7d.png)

So I am closing this issue as it is already possible to distinguish culverts from rivers.

@frodrigo Thanks for cooperation, the style PR is still welcome. And if you know about documentation of the `mapping` as you used in the patch, please paste a link here.

**Comment by frodrigo** [comment]
About the mapping of imposm3: https://imposm.org/docs/imposm3/latest/mapping.html#mapping

**Comment by jirik** [comment]
Thanks. I know this one, it documents `mapping` inside a table. However you used `mapping` inside a field, so it's a different case.

**Comment by frodrigo** [comment]
You right ! Maybe it do nothing, as I was already ok.
