### ISSUE TITLE
Severe errors in road and water

### ISSUE THREAD

**Issue by juho-hanhimaki** [openmaptiles/openmaptiles#381]
Compare:

https://openmaptiles.github.io/klokantech-basic-gl-style/#10/61.4693/23.8628

https://www.openstreetmap.org/#map=11/61.4693/23.8628

Lake Pyhäjärvi (>100 km^2) is missing completely.

Also some wild errors on Tampere western ring road.

Is this already using the latest 3.7 tiles?

**Comment by jirik** [comment]
Yes, it is 3.7. I've never seen something like Tampere western ring road problem before. Probably it's not problem in data.

Pyhäjärvi is maybe related to NE4 diacritics issue.

I am going to inspect it this week.

**Comment by juho-hanhimaki** [comment]
Also it seems the Pirkkala town label is at wrong place (something to do with the road problem?).

![image](https://user-images.githubusercontent.com/12390182/33828105-684c7d06-de73-11e7-8adc-6ef2da270656.png)

**Comment by jirik** [comment]
Maybe. Thanks for the report!

**Comment by jirik** [comment]
Note: Both errors appear also in 3.6.2.

**Comment by jirik** [comment]
I've just rendered the latest finland.pbf from geofabrik. Everything looks fine at Z6:
![image](https://user-images.githubusercontent.com/2271850/33842310-7511646c-de9a-11e7-816b-23c42c5d9b71.png)

We will probably wait for the next weekly planet update and check the result. Otherwise, we can render this part of Finland and merge it into planet.mbtiles.

**Comment by pathmapper** [comment]
@jirik looks like @freeman40 found the source of this issue and has a suggestion to prevent such things: https://github.com/openmaptiles/openmaptiles/issues/386#issuecomment-351497457

**Comment by freeman40** [comment]
@pathmapper I'm not sure the bad data that I referred to is related to this ticket.  This issue is about strange rendering of data that has already been imported.  The bad data in #386 prevents import-osm from completing -  so you don't have anything to render in the first place.

**Comment by pathmapper** [comment]
@freeman40 I am not 100% sure, my thoughts what both tickets have in common:

- It is the same area.
- It has been a problem in the past and with latest OSM data it seems to be fixed (@jirik tested it 3 days ago, the way you've found was fixed 7 days ago).

> The bad data in #386 prevents import-osm from completing - so you don't have anything to render in the first place.

I understood that this ticket here is related to vector tiles from https://openmaptiles.com/downloads/planet/ or https://www.tilehosting.com/ and they are likely rendered on a cluster by Klokantech. Maybe with their workflow it is still possible to render the tiles despite the invalid way but resulting in the issue described in this ticket.

**Comment by juho-hanhimaki** [comment]
This error is now partially fixed? It seems on some zoom levels it still persists.

https://openmaptiles.github.io/klokantech-basic-gl-style/#7/61.4693/23.8628

We've been considering the move into commercial hosting offering for long time now. However it's little troubling to us that major (imo) issues in data like these may take weeks or months to fix. I appreciate there may not be a simple solution but I hope the feedback is appreciated.

Is it always possible to use old version of tile data on the commercial hosting in case future update breaks stuff? For us its generally more important to have clean data/maps views than latest updates.

**Comment by jirik** [comment]
@juho-hanhimaki Did you clear your browser cache? The problem seems to be fixed at the link you've posted.

I am not sure why this error happen. I don't have any clear evidence it was related to #386. Maybe it was some very rare error of mapnik.

By default, services at tilehosting.com uses weekly planet updates. If you are interested in hosting specific planet tiles (e.g. without updates), it is possible with [Raster Pro](https://www.tilehosting.com/#plans) plan.

**Comment by juho-hanhimaki** [comment]
It is fixed now thank you. I though I tried clearing the cache before posting. Maybe the CDN cached the tiles? Does the CDN cache get invalidated on tile update?

Weekly updates are fine, but may put us into bad position if something breaks in major way in update. Customers will not be happy to see week (or worst case more) of bad quality maps.

But I suppose this is understandable trade off between cost and quality.

**Comment by jirik** [comment]
Yes, CDN caches tiles and it gets invalidated after update.

**Comment by juho-hanhimaki** [comment]
We bought the hosting service and now the same issue is on the back.

It can be seen on the main https://openmaptiles.org/ page too.

Free tiles are still working perfectly maybe because they use older data.

Is this correct channel to report problems on the commercial hosting service?

If we run to issues like this in production are we temporarily allowed to revert to using free cdn until the issue is fixed?

**Comment by jirik** [comment]
> Is this correct channel to report problems on the commercial hosting service?

No. Please next time report problems to info@klokantech.com - we will reply you there.

> Free tiles are still working perfectly maybe because they use older data?

Tiles at free.tilehosting.com are updated usually weekly and automatically. Tiles at maps.tilehosting.com are updated usually one week later after quality assurance period. This time it was delayed because of Christmas holidays.
