### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by CraigglesO** [openmaptiles/openmaptiles#385]
Hey guys, love this project. With a state, I can build a project no problem. However, with any other large scale project, I keep running into

```
SQL Error: pq: could not extend file "base/16384/614526": No space left on device in query CREATE TABLE
```

Issues like this. I tried a planet view, then I tried just North America, full project rather then the quick start MAX_ZOOM=7

I realize it's a partition issue inside docker (at least I think)

any suggestions how to bypass this?

**Comment by unibasil** [comment]
If there is quite enough space on your disks and you got "No space left" error, perhaps you should specify more inodes in file system (though I don't know how to do this in docker).

**Comment by jirik** [comment]
Hope it helps: https://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device

BTW This is a usage request - it should be at https://stackoverflow.com/questions/tagged/openmaptiles

**Comment by carlos-mg89** [comment]
Hi everyone,

I just got the same error, and I've been trying to empty space in my partition but I got to the point where I just can't go any longer. I've an SSD and it has physical limitations I cannot overcome.

Happily I do have a hard drive of 2TB (I'm with europe at the moment), and I'm quite sure it's definitely enough. The europe.osm.pbf is taking at least 130GB in my case, for zoom levels between 0 and 14. After that it crashes due to no space left on device. I'm trying to figure out if it's possible to set docker to take space from a different partition than the current/main one, where my Ubuntu is installed.

Thanks in advance :)

**Comment by kylebarron** [comment]
FYI I found I had to expand docker's virtual disk image:
https://stackoverflow.com/a/48561621

**Comment by prusswan** [comment]
This may need to be more explicitly documented for people trying a planet import: ran into this using WSL2 (which defaults to maximum of 256GB for vdisk, just moving the vdisk file to a physical drive with more space is NOT enough)

docker/for-win#9672
