### ISSUE TITLE
Localized tags not available for transportation_name

### ISSUE THREAD

**Issue by hannesj** [openmaptiles/openmaptiles#388]
In #279 basic support for multilingual maps were added. However, in the layer transportation_name, the localized names are not present. It seems that they were initially added, but removed in https://github.com/openmaptiles/openmaptiles/pull/279/commits/d53203dc4136851f7edef6cb23fec5d9587618ba. Is there some reason for not including them, and would you consider a PR that reverts the previously mentioned commit?

EDIT: I see the reason mentioned in https://github.com/openmaptiles/openmaptiles/pull/279/commits/82a1e2b7db96124c57d14c9558afcf7f73846d80. Would it be possible to drop the tags from the `group by` and change the logic to either take the first of the tags, or even merge if there are some keys missing.

**Comment by jirik** [comment]
Yes, you've found the reason why we removed it at that time. Maybe also because of performance.

Anyway, I think at that time we grouped transportation by **all** tags. The result was many short lines that were filtered out. However, we can try to use grouping by **language** tags only. It could give us much better results. The function `slice_language_tags` can be used for this as in case of waterway:
https://github.com/openmaptiles/openmaptiles/blob/3925c1b194c5981e4a273a25071d668f76f8bf12/layers/waterway/update_important_waterway.sql#L31

@hannesj PR for this issue is welcome. I suggest to try grouping using `slice_language_tags`. You can do revert process similar to https://github.com/openmaptiles/openmaptiles/commit/82a1e2b7db96124c57d14c9558afcf7f73846d80

**Comment by jirik** [comment]
Closed by #523
