### ISSUE TITLE
Waterway outside river polygon on z7-9

### ISSUE THREAD

**Issue by daliborjanak** [openmaptiles/openmaptiles#406]
Rivers are outside river polygons on zooms 7, 8 and 9. This is because rivers are generalized too much. See screenshots:

rivers - red colour
lakes - blue

Zoom 7-9 -river is outside polygon
![image](https://user-images.githubusercontent.com/1891090/34824113-763eb56a-f6cd-11e7-9ebc-6b60eb7a38cf.png)

Zoom 10 - river is in polygons
![image](https://user-images.githubusercontent.com/1891090/34824161-aa10e4bc-f6cd-11e7-851a-98026f009ad3.png)

Solutions:
Reduce generalization of rivers on critical zooms

**Comment by jirik** [comment]
The reason is rivers are taken from NE, but lakes are taken from OSM at Z6-Z8. Related to #310.

Solution is to unify switch between NE and OSM to one zoom level (in this case at least for waters).

**Comment by jirik** [comment]
@daliborjanak @klokan I can fix this one by showing generalized OSM for Z6-Z8 instead of NE, but another problem appear. Some river parts are missing:
![image](https://user-images.githubusercontent.com/2271850/38741367-196f0230-3f3a-11e8-8d7a-8f3239963eb7.png)
We already have the same problem problem in the schema for Z9+:
https://openmaptiles.org/inspect/#9.19/47.4760/7.5466
If I fix issue described by Dalibor, more rivers appear for Z6-Z8, but more river parts will be missing (see below). E.g. at Z6 most of river Aare is missing.

What's your opinion about it? Should it be fixed despite of missing river parts?

Suggested changes: https://github.com/klokantech/openmaptiles/commit/ac1d70fa3a869a9b86c969008bd5bc68dec8d4fa

Z9 (current, OSM)
![image](https://user-images.githubusercontent.com/2271850/38743302-0d8486de-3f3f-11e8-8353-7ecdb52a7d64.png)

Z8 (suggested, OSM)
![image](https://user-images.githubusercontent.com/2271850/38743279-f4b4ecc0-3f3e-11e8-8e09-a93d83419351.png)

Z7 (suggested, OSM)
![image](https://user-images.githubusercontent.com/2271850/38743344-26ef6774-3f3f-11e8-88dc-2c30cef8b9ed.png)

Z6 (suggested, OSM)
![image](https://user-images.githubusercontent.com/2271850/38743408-4c2a0544-3f3f-11e8-9d6b-b7c34397a789.png)

Z5 (current, NE)
![image](https://user-images.githubusercontent.com/2271850/38743582-c317c696-3f3f-11e8-9258-00fd58713172.png)

**Comment by daliborjanak** [comment]
So we can use this fix after #320 will be solved
