### ISSUE TITLE
Aral sea and circle nearby

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#416]
It seems that Aral sea has different shape on different zooms, and there is some garbage circular line nearby. Happens in several recent planet updates, including today's. Probably lower zoom (zoom<=5) data has old/invalid data which is not updated?

[openmaptiles-aral.mov.zip](https://github.com/openmaptiles/openmaptiles/files/1655414/openmaptiles-aral.mov.zip)

<img width="502" alt="screenshot 2018-01-23 11 17 32" src="https://user-images.githubusercontent.com/5609650/35270299-07f71b5e-002f-11e8-9866-63773c7d7fae.png">

**Comment by almccon** [comment]
The circle is real. It's a part of Russia within Kazakhstan surrounding the Baikonur Cosmodrome: https://en.wikipedia.org/wiki/Baikonur_Cosmodrome

Natural Earth includes it as an international border, but OSM doesn't (because technically it's just a long-term lease, not a permanent transfer of territory) which is probably why it appears at some zooms, but not at others.

Same thing with the Aral sea, that's most likely because Natural Earth uses a different shape as compared to OSM.

**Comment by nvkelso** [comment]
It's possible to filter the Baikonur Cosmodrome out in Natural Earth, as
well as other lease areas as those are tagged in the attributes.

Sounds like either Natural Earth or OSM needs to update their shapes....

**Comment by jirik** [comment]
I think the circular border can be filtered easily and that we should remove it completely.

**Comment by jaakla** [comment]
Russians are working on moving Baikonur to Vostochny Cosmodrome, so this circle should disappear eventually. Until that I could live with it; I just thought it was a map mistake. 

Unfortunately  no one doesn't seem to do anything to refill the Aral sea, which would be the correct resolution to the second issue.
