### ISSUE TITLE
Missing major sea names

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#434]
I cannot find many major marine (sea) names from data or preview map, while smaller ones are somehow present:

* Caribbean Sea https://www.openstreetmap.org/node/305640123
* Mediterranean Sea https://www.openstreetmap.org/node/305640275
* Caspian Sea
* Sea of Japan
* Celtic Sea
* Chukchi Sea (https://www.openstreetmap.org/relation/5852766)

I'd consider some bays also:
* Bay of Biscay https://www.openstreetmap.org/relation/7156290
* Gulf of California https://www.openstreetmap.org/node/305639734

Some could be missing from OSM data, did not do full search.

**Comment by jirik** [comment]
Corresponding OSM features:
- Caspian Sea: https://www.openstreetmap.org/relation/3987743
- Sea of Japan: https://www.openstreetmap.org/node/2483364661
- Celtic Sea: https://www.openstreetmap.org/node/305639697
- Chukchi Sea: https://www.openstreetmap.org/node/305640107
- Gulf of Biscay: https://www.openstreetmap.org/node/1627075382

**Comment by jirik** [comment]
Most of these cases should be fixed by 24caa53. Some will be not fixed:
- We are not importing sea relations now, only sea nodes. E.g. Caspian Sea is represented only by relation, not by node, so it will not be imported. In these cases I prefer to add nodes to OSM (if possible).
- Celtic Sea is not contained in Natural Earth (ne_10m_geography_marine_polys) that is authority in this case.
- [Gulf of Biscay](https://www.openstreetmap.org/node/1627075382) is tagged with `place=bay`. I think it's a bug and it should be changed to `place=sea`. After this fix, also Bay of Biscay will be imported.
