### ISSUE TITLE
Missing islands in Norway near Oslo

### ISSUE THREAD

**Issue by heikkipora** [openmaptiles/openmaptiles#447]
OpenStreetMap has islands that are missing from OpenMapTiles vector tileset

## OpenStreetMap:
![image](https://user-images.githubusercontent.com/259924/39045206-e7c24a6a-449a-11e8-99bb-890c3b48afe7.png)

## OpenMapTiles:
![image](https://user-images.githubusercontent.com/259924/39045236-fcd653ce-449a-11e8-8713-a82285827274.png)

**Comment by jirik** [comment]
Island (or generally land) polygons are not encoded in openmaptiles. Only water polygons are. The rest of the planet is considered as land.

The problem here is that water polygon Bunnefjorden does not contain "holes" of islands, so it's data related issue.
https://www.openstreetmap.org/relation/6812187

Solution: Add island holes to Bunnefjorden relation.

**Comment by pathmapper** [comment]
Fixed it in https://www.openstreetmap.org/changeset/64195387.

**Comment by jirik** [comment]
@pathmapper Great, thank you!

**Comment by heikkipora** [comment]
Thanks! (also for the clarification of how water & land works in openstreetmap dataset :-) )
