### ISSUE TITLE
Invalid labels in China

### ISSUE THREAD

**Issue by AliFlux** [openmaptiles/openmaptiles#456]
Hi.

I recently downloaded the complete Asia mbtiles from openmaptiles.org. Upon usage, I found out that the labels of certain places seem corrupted. I used maputnik to inspect the issue and independently verify if the same happens using `tilehosting.com` tiles or not.

![valid](https://user-images.githubusercontent.com/8333794/40540119-71c072ae-6030-11e8-9fb0-65e01e59d2fb.PNG)
`Klokantech Basic Style` with `https://free.tilehosting.com/data/v3.json?key={key}` source

![invalid](https://user-images.githubusercontent.com/8333794/40540150-9058e408-6030-11e8-8ec4-9a6cc884ae73.PNG)
`Klokantech Basic Style` with `http://127.0.0.1:8080/data/v3.json` source (served using tileserver-gl-lite, uses Asian mbtiles downloaded from `openmaptiles.org`).

I also used the inspect tool at maputnik to further verify the issue.

![valid inspect](https://user-images.githubusercontent.com/8333794/40540241-dd564250-6030-11e8-9b16-406ffe6e73a8.PNG)
Inspecting the city label of tilehosting.com tile

![invalid inspect](https://user-images.githubusercontent.com/8333794/40540259-ec5c9a4c-6030-11e8-9a6c-d6722e89b975.PNG)
Inspecting the city label of openmaptiles.org mbtile data

At first, it seemed like the issue could be in reading the mbtiles. But the db was double checked for integrity and the data inspection was conducted using another tool as well.

**Comment by ImreSamu** [comment]
Thank you for your feedback.

You can check the data sources to find the root cause of the problem.

As I see (now)  there are  ~ 2  "Karakax" :  https://www.openstreetmap.org/search?query=Karakax#map=8/37.291/79.744

####   https://www.openstreetmap.org/node/452737932
* place = town
* https://www.wikidata.org/wiki/Q10923366 ( town in China )

#### https://www.openstreetmap.org/node/4637658395  ( probably you see this )
* place = city
* name:en = Karakax/Moyu
* https://www.wikidata.org/wiki/Q1207811 (  county of China ?!?!?! )  maybe a bad link  ?

**Comment by AliFlux** [comment]
This could be the reason. But the main issue is that the labels in the tile are not valid. `name_en` is supposed to be an english name but its arabic for some reason. According to both of these wikidata links, `name_en` is supposed to be either `Karakax` or `Karakax/Moyu`, not `قاراقاش ناھىيىسى`.

**Comment by MartinMikita** [comment]
Dear AliFlux, what OMT schema MBTiles have you downloaded? Because a free download from openmaptiles.org is from the old schema v3.6. Now there is OpenMapTiles schema v3.8, and there were improvements on the translations (see the release notes for v3.7).

The name is correct on free.tilehosting.com, therefore you seem to be using the old data.

This is not the bug of OpenMapTiles project. You can either generate your data by your own, or you can download the newer dataset from https://openmaptiles.com/downloads/asia/

**Comment by AliFlux** [comment]
That makes sense. The free package is at version 3.6, right now. Can I know when the free tiles are being updated to version 3.8?
