### ISSUE TITLE
Transparent islands in France

### ISSUE THREAD

**Issue by maxkey** [openmaptiles/openmaptiles#458]
OpenStreetMap has normal islands that are transparent at OpenMapTiles. There are no land polygons in OpenMapTiles vector tileset at this place. 
https://maputnik.github.io/editor/#10/46.0698/-1.4028

**OpenMapTiles:**
![image](https://user-images.githubusercontent.com/5227492/41092373-65a69d24-6a51-11e8-8708-7688aea7e0a5.png)

**OSM:**
![image](https://user-images.githubusercontent.com/5227492/41092388-6ddde1be-6a51-11e8-9777-9eef7afda6ff.png)

**Comment by freeman40** [comment]
This is a layer ordering issue.  The water layer is drawn over the top of the landcover areas, and so hides the islands.

**Comment by pathmapper** [comment]
Most of the island areas "missing" are `class = wetland` (from source layer `landcover`) and 
`class = lake` (from source layer `water`). 

On the OSM screenshot there are no such big lakes visible, so `class = lake` is likely a problem with the vector tile source. 

The missing `wetland` layer could be added to the style but could have side effects for other areas. 

The problem exists also with other OMT styles.

**Comment by jirik** [comment]
It's not layer ordering issue. We do not encode islands (or generally land) polygons into openmaptiles. The problem here is that water filled islands in Bay of Biscay, because someone broke it's outer ring few weeks ago. I've fixed it 3 days ago:
https://www.openstreetmap.org/changeset/59569530
The fix should be automatically propagated to free.tilehosting.com next week.
