### ISSUE TITLE
Getting 404 Tile not found

### ISSUE THREAD

**Issue by michaelknave** [openmaptiles/openmaptiles#483]
I am using Self Hosted **OpenMapTiles** solution. I have followed the instructions from https://openmaptiles.org/docs/generate/generate-openmaptiles/ . 

I have all set it up, downloaded and preprocessed dataset. 

After I start server, go to the vector tile map I am getting 404 http://i.prntscr.com/fFFIoAXFTKKUQpVQT3SWnQ.png almost on every tile. 

I am running on Ubuntu 16.04.

**Comment by klokan** [comment]
Try it with the downloaded MBTiles from https://openmaptiles.com/downloads/. Does it run for you (so no 404)?

If yes - then something is wrong with the tiles you generated (you can look into SQLite) or with the process you have used to generate the tiles...

There are no technical details in your issue - neither what region you generate, what commands you have used nor what server you use to serve the tiles. The problem is not possible to reproduce.

**Comment by michaelknave** [comment]
Thanks for your response. I was experiencing it yesterday with the Malta and Estonia regions. 

Today I tried it one more time with different countries and it fully works right now.
