### ISSUE TITLE
Missing great lakes on z6+

### ISSUE THREAD

**Issue by guyisra** [openmaptiles/openmaptiles#491]
Generate the tiles from the chicago area it seems that some lakes disappear from z6 onwards

I realize this occurs right on the switching point from NE to the osm data, but I dont understand what is causing *that* to disappear, yet the lake next to Cleveland stays put
![great_lakes2](https://user-images.githubusercontent.com/1073521/44138371-62a2e586-a07c-11e8-8e55-41f2b1df7bdd.gif)

The style is the basic style, its a bit darker because the gif resolution resize

**Comment by ImreSamu** [comment]
> I dont understand what is causing that to disappear

maybe a data problem (OSM ) and related to this issue: 

"[OSM-talk] 2 Great Lakes missing"
https://lists.openstreetmap.org/pipermail/talk/2018-August/081232.html

**Comment by FaizAli07** [comment]
As far as I can understand, with my limited knowledge on the same, this seems to be the data rendering issue of the OSM after z6+ as when more locality name layers come into the view, the layers/polygons of the 2 greater lakes overlap with the locality names and seems to be going beneath the locality names layer. The tile/polygon close to Cleveland stays as it might not be of the same layer of that of other two lakes or it might be created or added to the OSM separate. 

This is just my point of view/understanding open to discussion.

**Comment by MartinMikita** [comment]
It seems, that this problem is the same as described for another area - #509 

The problem could be of missing some ways/nodes of the relation in the GeoFabrik region exports, and `imposm3` (or OGR library) is not able to reconstruct this relation to be in Postgres DB.

Are you able to validate this theory by investigating this relation and missing ways in the source OSM.PBF?
Otherwise, as this is not a problem with the planet, nor the OpenMapTiles schema, we would consider this as a not fixable problem of the `imposm3` utility (or actually missing data from GeoFabrik) and close this ticket.
