### ISSUE TITLE
Beach in western Washington, US, appearing as water

### ISSUE THREAD

**Issue by procogent** [openmaptiles/openmaptiles#520]
There is a section of beach in western Washington, USA that is rendering as water when it should be land.

It is visible in the demo map on openmaptiles.com, as well as the style examples on openmaptiles.org.

https://openmaptiles.com/downloads/dataset/osm/#15.68/46.9311/-124.1744/0/1

https://www.maptiler.com/maps/#streets//vector/14.41/-124.16796/46.95557

![2018-10-29_13-41-46](https://user-images.githubusercontent.com/20845025/47814380-cc316200-dd0a-11e8-81b5-05a76899ce78.png)

**Comment by Bibi56** [comment]
Even if the style could render it properly, the issue IMHO is more related to the data; instead of describing the beach as a way, it's described as a multipolygon, using the coastline and another way as outers.

Usually a beach goes on both sides of the coastline, one part submitted to tidal, the other not.

**Comment by jirik** [comment]
Agree, it's data-related. However, it can be solved also by style.
https://github.com/openmaptiles/osm-bright-gl-style/commit/918441b7c8f130d32f34ecd210f01daf59934cf2

Preview:
![image](https://user-images.githubusercontent.com/2271850/48501013-75647600-e83c-11e8-8844-19eb76d49119.png)
