### ISSUE TITLE
Missing islands - prevent recurring issues by cutting the water polygons

### ISSUE THREAD

**Issue by jirik** [openmaptiles/openmaptiles#522]
There are quite many recurring issues with missing islands, e.g. #458 #447 #519 . Cause was either bug in water relation (#458) or island holes not presented in water polygon (#447 #519).

As @pathmapper pointed out
> > There is currently no definitive rule if small islands within a bay should be mapped as part of the bay or if they should be excluded of the bay area as inner rings of the corresponding multipolygon relation.

> (from https://wiki.openstreetmap.org/wiki/Tag:natural=bay)

> Maybe it's worth to think about to start a discussion whithin the OSM community whether there should be a definitve rule to exlude islands from bay areas.

(from https://github.com/openmaptiles/openmaptiles/issues/519#issuecomment-435859020)

Maybe it's also possible to prevent similar issues by importing [islands](https://wiki.openstreetmap.org/wiki/Tag:place%3Disland) and [islets](https://wiki.openstreetmap.org/wiki/Tag:place%3Dislet) polygons and erase their area from water polygons (tables `osm_water_polygon`, `osm_water_polygon_gen*`). Special attention should be paid to update logic.

**Comment by pathmapper** [comment]
Another example is in https://github.com/openmaptiles/openmaptiles/issues/574, and in this case fixing it manually like in #447, #519 is not appropriate because there are too many single islands.

https://www.openstreetmap.org/relation/9048256#map=10/60.1938/20.3096

![image](https://user-images.githubusercontent.com/20856381/52626045-a4799a80-2eb2-11e9-9ca1-207d1f63fad3.png)
