### ISSUE TITLE
osm_ids being enlarged by the layer functions and causes  'bigint out of range' when the osm_ids are very big 

### ISSUE THREAD

**Issue by einavh** [openmaptiles/openmaptiles#544]
hello,
when generating vector-tiles I get an error of bigint out of range.
after investigation I found out that the layers functions are making the osm_ids bigger and that is the root cause of the error.
can you explain why you are making the osm_ids bigger ?

**Comment by MartinMikita** [comment]
The root cause is, that `osm_id` number from PBF is invalid.
This happened a few times ago, when the number was `-1`, but converted into an unsigned integer, it overflowed and cannot be multiplied.

This is the problem of the source data. The multiplication by 10 should be enough for all osm_id values in OpenStreetMap database.
