### ISSUE TITLE
Understanding OMT with Mapbox

### ISSUE THREAD

**Issue by lhorus** [openmaptiles/openmaptiles#632]
I've been using a quite cumbersome pipeline to create .mvtiles with small size - by removing unwanted tags - which I can then compress and send to mobile devices for offline rendering. Currently, I'm taking a GeoFabrik extract, filtering it (as much as I can, although there are an incredible amount of tags to ignore), converting to GeoJSON, using tippecanoe to glue multiple GeoJSON sources, split the whole thing into smaller chunks according to specific geoboundaries, and then take the mvtiles. So, I'm turning to OMT to try to simplify this whole thing, I do have some questions though:
- Can OMT extracts be used directly with Mapbox Styles? (for instance, mapbox-streets-v8)
- Can one add/remove custom layers, as well as default ones?
- Does OMT's quickstart.sh remove junk tags not used in styles (for instance, author, max_speed roof)?

**Comment by nnhubbard** [comment]
> Can OMT extracts be used directly with Mapbox Styles? 

Yes!

> Can one add/remove custom layers, as well as default ones?

You can remove the code for specific layers that you don't want included and they won't be in final `mbtiles` file. Alternately you can create custom layers as well.

> Does OMT's quickstart.sh remove junk tags not used in styles (for instance, author, max_speed roof)?

Yes, it only includes the data specified in the layers/mapping files.

**Comment by freeman40** [comment]
OMT generated tiles can be used with styles specified in the mapbox style format, but I'm not sure the style files from mapbox (e.g. mapbox-streets-v8) will work directly (since the layer and tag names will be different to what is in an OMT generated mbtiles).  You can, however, upload your mbtiles file (e.g. to mapbox studio) and a tool to author your own style.

The OMT pipeline will only include data specified in layers/mapping files.  If you know what style you are going to be rendering the data with, then you can optimize the layers/mapping files to only include tags used in the style.

**Comment by lhorus** [comment]
Thanks for the answers guys!


> OMT generated tiles can be used with styles specified in the mapbox style format, but I'm not sure the style files from mapbox (e.g. mapbox-streets-v8) will work directly (since the layer and tag names will be different to what is in an OMT generated mbtiles). You can, however, upload your mbtiles file (e.g. to mapbox studio) and a tool to author your own style.
> 

That was my main concern, I'll try to find some references on their tags and conversion to OSM-based tags.
