### ISSUE TITLE
relation "osm_water_polygon_gen6" does not exist

### ISSUE THREAD

**Issue by AnaalNathrakh** [openmaptiles/openmaptiles#661]
I followed the tutorial, but "make import-sql" fails with:
     relation "osm_water_polygon_gen6" does not exist

I checked all previous steps, but could not find a place where osm_water_polygon_gen6 is generated

**Comment by AnaalNathrakh** [comment]
may be an error on my part ... running quickstart works

**Comment by carlos-mg89** [comment]
I had a similar error (was with wd_names instead of osm_water_polygon_gen6) while running the manual commands, instead of the quickstart. However, it's troublesome, since quickstart is longer than just importing a whole map, and then generate smaller mbtiles using the bounding boxes. Would be great to help with fixing this.

**Comment by klokan** [comment]
Please run `docker-compose run import-water`
