### ISSUE TITLE
show street names below zoom 14?

### ISSUE THREAD

**Issue by andredoering** [openmaptiles/openmaptiles#673]
Hey I posted it already on tileserver-gl, but I am not sure what the issue is, if tileserver-gl or OpenMapTiles is responsible for that, so I ask here too (sorry if it is a duplicate)

Is there an option that the street names are visible for vector tiles, below zoom 14.
I don't need to show all the POI, I just need to show the street names at zoom 13.

Can I set that up in the config somehow? What can I do? Thank you!

**Comment by eva-j** [comment]
Hi @andredoering, you can display street names already at zoom 13 or even 12. If they are not displaying for all the streets you need, you can edit generalization criteria for the zoom level in `transportation_name` layer. E.g. for zoom 13, you can find it here: https://github.com/openmaptiles/openmaptiles/blob/master/layers/transportation_name/layer.sql#L104-L105
- there is LineLabel function (https://github.com/mapbox/postgis-vt-util/blob/master/src/LineLabel.sql) to put away the labels that would not fit on the line because geometry is too short for them
- highways of the class (https://github.com/openmaptiles/openmaptiles/blob/master/layers/transportation/class.sql#L12) 'track' and 'path' are not displayed
