### ISSUE TITLE
Understanding how mountain_peak rank is calculated

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#687]
I am trying to understand how the `rank` is calculated for `mountain_peak` layer. It is:

```sql
       row_number() OVER (
           PARTITION BY LabelGrid(geometry, 100 * pixel_width)
           ORDER BY (
             substring(ele from E'^(-?\\d+)(\\D|$)')::int +
             (CASE WHEN NULLIF(wikipedia, '') is not null THEN 10000 ELSE 0 END) +
             (CASE WHEN NULLIF(name, '') is not null THEN 10000 ELSE 0 END)
           ) DESC
       )::int AS "rank"
```

How is this working to rank the peaks? I am not good with SQL, so I am not familiar with what is happening here. Any help?

**Comment by typebrook** [comment]
Use current feature as center, compare with other features in the range of 100 pixel.
Order them decently with a **value** calculated by:
- elevation(m)
- if this feature has key "wikipedia", value += 10,000
- if this feature has key "name", value += 10,000

then we got the **rank** of this feature

---
In conclusion, to judge the rank value of a peak feature, the importance is:
`wikipedia page` = `name` > `elevation`
because the highest mountain is about 8,848m

And this also reminds me, we should include key `wikidata` as consideration in this case, but with less weight maybe 2,000.

**Comment by nnhubbard** [comment]
Thank you!

**Comment by kylebarron** [comment]
> And this also reminds me, we should include key `wikidata` as consideration in this case, but with less weight maybe 5,000.

I've noticed some `natural=peak` tags have `wikidata` tags but no explicit `wikipedia` tag. But since you can (always?) find the wikipedia article from the wikidata string, I'd suggest 
```
if feature has key "wikipedia" or if feature has key "wikidata", value += 10,000
```

**Comment by typebrook** [comment]
@kylebarron 
> you can (always?) find the wikipedia article from the wikidata string

This is not true, a wikidata item will be automatically created with a wikipedia article by bot.
But you can always create wikidata items as you wish (like I dumped some government open data into it)

> `if feature has key "wikipedia" or if feature has key "wikidata", value += 10,000`

Just my opinion, an osm feature which has a wikipedia article should weights more than others only has a wikidata link.
