### ISSUE TITLE
import-osm docker no longer downloading US Sub Regions

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#705]
For some reason in the last week the `import-osm` docker step `make download-geofabrik area=us-west` is no longer downloading or finding the US Sub Regions. They ARE still available for download on the `Geofabrik` website:

[https://download.geofabrik.de/north-america.html](https://download.geofabrik.de/north-america.html)

Did something change with that docker image to make this no longer work?

**Comment by julien-noblet** [comment]
I will try to fix it in https://github.com/julien-noblet/download-geofabrik/ please have a look at https://github.com/julien-noblet/download-geofabrik/issues/217

**Comment by nyurik** [comment]
Note that the [import-osm image](https://hub.docker.com/repository/docker/openmaptiles/import-osm/tags?page=1) has not been re-built since June 11, 2018 due to a very old packages it requires.  Any pull requests merged in the last year were not included. The `migrate-2019-11-15` tag is a copy of that latest, so when we finally fix the latest, the one from 2018 will still be around (tagged with the migration tag).  This also means that https://github.com/openmaptiles/import-osm/commit/68a6c8373363bc68c989fe1507121e6ca03cf5a2 was the last patch that went into the image, and all [these changes](https://github.com/openmaptiles/import-osm/compare/d862ad3135e7f6f47229a1eed9b148c0666f7c6e%5E...master) did not.  cc: @eva-j @klokan @daliborjanak 

![image](https://user-images.githubusercontent.com/1641515/68987158-0c1f9600-07f5-11ea-92cc-c1186098077c.png)

**Comment by nnhubbard** [comment]
@julien-noblet @nyurik Has anything changed recently with this docker image? `us-west` always worked up until about 2 weeks ago.

**Comment by nyurik** [comment]
@nnhubbard which image?  `import-osm` has not changed for the past year because of a docker build error.

**Comment by nnhubbard** [comment]
@nyurik Just using the normal `quickstart.sh` script, which in turn uses `docker-compose run --rm import-osm  ./download-geofabrik.sh $(area)`. I have multiple servers running this and they all stopped downloading `us-west` recently.

**Comment by nnhubbard** [comment]
I was able to fix this by manually updating `download-geofabrik` in my docker image.

**Comment by TomPohys** [comment]
From OpenMapTiles-Tools v4.1 is implemented new `download-osm` and now is possible to download us-west -> https://github.com/openmaptiles/openmaptiles-tools/releases/tag/v4.1.0

thanks @nyurik
