### ISSUE TITLE
Rhode Island and Massachusetts Not Generating admin_level 6 boundary LineString

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#763]
For whatever reason, if I run `./quickstart.sh rhode-island` it is missing the county borders (admin_level 6) at any zoom level. Running the script on other states such as `Connecticut` generates those `LineStrings` as I would expect.

Checking overpass turbo it shows that OSM does have `admin_level` 6 data: https://overpass-turbo.eu/s/PD8

Does anyone know what the issue might be here? And why it imports for some US States but not others?

**Comment by maxammann** [comment]
![image](https://user-images.githubusercontent.com/905221/107773931-a6df8b00-6d3e-11eb-9c9f-825b6b1245a2.png)

I have a similar problem. Borders of the admin_level 2 are only partially available. Admin levels 3 to 10 are not available at all.

**Comment by TomPohys** [comment]
Hi @nnhubbard, sorry for the late answer. I just tested `./quickstart.sh rhode-island` and everything seems fine. Please, make sure, that folder `/data/borders/ is empty. Otherwise, it will not recreate the `filtered.pbf` and `lines.csv` and `import-border` will import "old" boundaries.

![rhode-island_boundary](https://user-images.githubusercontent.com/5182210/107780632-3a1cbe80-6d47-11eb-9ac5-ac3e638b4662.png)

**Comment by TomPohys** [comment]
Hi @maxammann, what data source (steps) did you use? It looks like there is some cutline, which is not corresponding with OSM.

**Comment by maxammann** [comment]
@TomPohys I used `./quickstart europe/germany` from the master a few days ago. I'm retrying to render it now with v3.11.

Maybe it was something similar as for @nnhubbard. Maybe it did not execute the import-borders correctly because of some stale files. I just saw in the output of the new generating that it does import the borders correctly. So lets see.

After that I will regenerate it with the lastest released version if it works. Thanks for the awesome work you put into this project!

**Comment by TomPohys** [comment]
I tested `./quickstart sachsen` and it looks OK. I am using the `master` branch. 
 
![Screenshot from 2021-02-12 15-49-42](https://user-images.githubusercontent.com/5182210/107782960-faa3a180-6d49-11eb-8cee-c0ef5f164f3d.png)

**Comment by maxammann** [comment]
I'm not a 100% sure yet but I maybe stumbled into this issue but ignored the error message: https://github.com/openmaptiles/openmaptiles/issues/901

Also getting the osm data from FR and now I set BORDERS_CLEANUP=true. Lets see

**Comment by TomPohys** [comment]
Hi @nnhubbard and @maxammann , was the issue solved on your side?

**Comment by maxammann** [comment]
yes, for me the issue was that I had to restart the process and BORDERS_CLEANUP was false. After cleanup and rebuilding it worked.
