### ISSUE TITLE
Housenumber duplicates

### ISSUE THREAD

**Issue by eva-j** [openmaptiles/openmaptiles#766]
E.g. in Kaunas, Lithuania (18/54.89617/23.88801)
![house_no_labels_dublicates](https://user-images.githubusercontent.com/8367628/72275966-43f95d00-362f-11ea-988d-7439d00b762d.png)

Housenumbers are imported as points and polygons:
![Screenshot from 2020-01-13 18-06-44](https://user-images.githubusercontent.com/8367628/72276112-8458db00-362f-11ea-99c2-f87dc92729d8.png)

Then polygons are transformed into points, so in the end we see e.g. 3 times number 8.

We should probably first remove points laying on polygon and then make Centroid/PointOnSurface of the polygon (only the second part is done in https://github.com/openmaptiles/openmaptiles/blob/master/layers/housenumber/housenumber_centroid.sql#L8-L13).

**Comment by pnorman** [comment]
This sounds like a data bug, not a style bug

**Comment by golubev** [comment]
The same issue can be seen here (a shopping mall) - https://www.maptiler.com/maps/#streets//vector/17.54/30.523463/50.412717

![Screenshot from 2020-06-11 17-49-29](https://user-images.githubusercontent.com/951364/84401457-f4ce4d00-ac0b-11ea-9dd4-22f2453036f7.png)

It seems to me that the root cause of my issue has to deal with POIs (as they can have an address) and with the next extracts:
https://github.com/openmaptiles/openmaptiles/blob/447a8380e0435dcef729c32ee0eb76d3ea648c8e/layers/housenumber/housenumber.yaml#L1-L5
https://github.com/openmaptiles/openmaptiles/blob/447a8380e0435dcef729c32ee0eb76d3ea648c8e/layers/housenumber/mapping.yaml#L15-L21

**Comment by frodrigo** [comment]
For me it is also a data issue, not OpenMapTiles one.
POI may be be tagged with `contact:housenumber` https://wiki.openstreetmap.org/wiki/Key:contact

**Comment by eva-j** [comment]
@frodrigo thanks for your comment - you are right, it would be fine if all the POIs use `contact:housenumber`, but unfortunately it's not the case.

**Comment by eva-j** [comment]
For now there is no quick enough solution (see #1005). Possible workaround is to switch `addr:housenumber` to `contact:housenumber` tag in OSM for POIs in problematic localities.

**Comment by golubev** [comment]
Okay, thanks @eva-j! :raised_hands:
