### ISSUE TITLE
Osm_id hided from tiles in mountain_peak and aerodrome

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#804]
This PR https://github.com/openmaptiles/openmaptiles/pull/686 hide osm_id in generated tiles. 

osm_id should be available. It will also help #792  

Should be `key_field_as_attribute: true`

**Comment by nyurik** [comment]
MVT objects have a concept of a `feature ID`. Each feature could have a non-negative ID number which is stored as `id` column

 `key_field_as_attribute` in MVT Postgis from what I understood. 

Questions that we need to resolve:
* Should `osm_id` be included in the MVT?  (I assume the answer is yes)
* Should `osm_id` be included as a regular property, or as the feature ID, or both?  Using [MVT spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#42-features) (see also [MVT docs](https://docs.mapbox.com/vector-tiles/specification/)), our options are:
  * to not use `key_field` at all: `SELECT osm_id ...` will simply become a regular column, without affecting the `feature ID` property. The value is accessible via `["get", "osm_id"]` in the style.
  * use `key_field` to use `osm_id` as a `feature id`. Styling can always use it via the `["id"]` [docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#id) expression.
  * use `key_field_as_attribute = yes` -- I suspect this will place `osm_id` as two values inside the feature -- as the `id` AND as the `osm_id` property, making it accessible via both methods listed above.  I don't think we should go this route -- why increase the storage size unless there are some other limitations i'm not thinking about?
```
  
```

**Comment by daliborjanak** [comment]
Context: With the last release and removing the ```osm_id ``` brokes applications of our customers. I would like to preserve this information somewhere ideally with non-breaking change which happened. It is removing the possibility to get other data from OSM and linking with other related interactions. 

The same problems may happen on buildings if https://github.com/openmaptiles/openmaptiles/pull/725 will be merged

**Comment by klokan** [comment]
We definitely want OSM IDs in the MVTs - as it brings a lot of options for various applications. Picking and getting additional info (popups with opening hours, link to databases, etc), as well as styling objects differently based on their IDs, are examples.

The ability to read hardcoded `feature id` from MVT in styles is new to me - it has been added with the support of expressions in GL styles. Before `feature id` was accessible only from JavaScript APIs - not from styles.

We have to check whether it is sufficient for all use cases.

**Comment by nyurik** [comment]
`feature id` has this in the docs:

> A feature MAY contain an id field. If a feature has an id field, the value of the id SHOULD be unique among the features of the parent layer.

My understanding is that there should be no more than one unique ID per layer per tile.

It sounds like a better path forward for OSM IDs (it seems like a good fit for this feature). But if you want to maintain backwards compatibility, we can simply declare `osm_id` as a regular field, and remove `key_field` and `key_field_as_attribute`.

**Comment by pathmapper** [comment]
[Feature state](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#feature-state) is a powerful use case which requires a `feature id`. So for this case it would be good to have the OSM IDs as feature IDs available in the tiles.  

From https://docs.mapbox.com/help/tutorials/create-interactive-hover-effects-with-mapbox-gl-js/

> For vector sources [...] that are added before runtime, you must set a unique id for each feature before the source is added to the map.

**Comment by ladislavhorky** [comment]
Hello, thanks for taking look at this. Here is my input as an originator of the issue.

For the time being we implemented the workaround and use the feature id from `mountain_peak`.

From point of view of our use-case, having OSM ID as `feature id` is completely fine (and maybe even more consistent), as long as this is documented. For me a go-to documentation about tile contents is https://openmaptiles.org/schema/ - if there is some more information that is implicitly present in the data format (e.g. the `feature id` if I understand correctly), any link to the deeper description of the format would be appreciated.

As a note, `place` layer (with cities) has the OSM ID with a trailing 0 (or OSM ID * 10) as `feature id` so that may be another thing to look at if OSM ID is going to be supplied as `feature id` in the future.

**Comment by ZeLonewolf** [comment]
In #1147 I propose to remove `osm_id` from the intermediate tables in the `transportation_name` layer because it is not presently being used.  In that case, each `transportation_name` object is a merged, and at lower zooms a generalized geometry, which would not have a single `osm_id` associated with it.  Is there a desire to create a `feature_id` for all cases to uniquely identify features, even when they don't map to a single `osm_id`, or only in cases such as this where there is a clear 1:1 mapping with an OSM feature?
