### ISSUE TITLE
Missing land at zoom levels 6/7

### ISSUE THREAD

**Issue by michalc** [openmaptiles/openmaptiles#885]
I'm using the MVT generation from Postgres solution, i.e. generated using
```
./openmaptiles-tools/bin/generate-sqltomvt --postgis-ver=2.4.4 openmaptiles/openmaptiles.yaml
```
The postgis version is specified to work on AWS Aurora

At some zoom levels sometimes land can be missing. I have noticed it around the UK (in the screenshot) and in Florida. Not noticed this elsewhere.

<img width="1239" alt="Screenshot 2020-05-21 at 21 20 41" src="https://user-images.githubusercontent.com/13877/82602762-7c92df80-9ba9-11ea-955f-2ead0619f45f.png">

It does feel as though the tiles have loaded: when zooming in the text/roads detail increases at the exact moment the land disappears.

This taken on Chrome on Mac, using Postiron https://github.com/openmaptiles/positron-gl-style

**Comment by nyurik** [comment]
There were some bugs in Postgis before 3.0.1 that dropped some polygons, so this could be related.  Another issue I have observed is that the very latest ogr2ogr began handling errors a bit differently when loading natural earth polygons, and on zoom5 it hid many water polygons when using with PG12.  I have not observed any issues with Postgis 3.0.1 though.

**Comment by michalc** [comment]
> There were some bugs in Postgis before 3.0.1 that dropped some polygons, so this could be related.

Ah unfortunate for getting this working on Aurora, which AFAIK does not offer 3.0.1

Interestingly, I have also noticed the same thing around Panama. The UK, Florida and Panama have quite high water to land ratios on the tiles in question...

**Comment by michalc** [comment]
A bit more info: an example tile in question is z/x/y: 6/31/20 (part of the UK).

And, if in `osm_ocean_polygon_gen4` I change to `ST_Simplify` to `ST_SimplifyPreserveTopology`, the land seems to be as it should be. Perhaps the simplification doesn't handle being on multiple sides of an island well?

**Comment by ianthetechie** [comment]
Speaking from my own experience, this is probably not an issue with OMT itself, but a postgis issue. Though as you correctly note, many PostGIS functions do not guarantee that the resulting geometry is valid. In general, the geometry engine used for postgis < 3.x had a lot of issues and didn't handle these situations well. The new engine used for MVT geometry generation ("rendering"), wagyu, is much better and also happens to be faster most of the time. I would highly recommend PG 3.x if at all possible. I've been running it since the alpha releases and it's much better.

**Comment by TomPohys** [comment]
Hi @michalc, did the change of polygon simplification or update to PostGIS 3.x resolve the problem with missing lands?
