### ISSUE TITLE
Generalization rules for the transportation layer merge matviews seem ad hoc

### ISSUE THREAD

**Issue by brncsk** [openmaptiles/openmaptiles#966]
The rough structure of the statements creating the `osm_transportation_merge_linestring_gen*` matviews is the following:

```sql
CREATE MATERIALIZED VIEW osm_transportation_merge_linestring_gen* AS (
  SELECT ST_Simplify(geometry, <tol>) AS geometry, [...]
  WHERE [...] AND ST_Length(geometry) > <len>
);
```

...where the values for `<tol>` and `<len>` are `120`, `200`, `500` etc.
Question: what was the exact line of thinking behind these choices? Wouldn't it be better to derive these values from `zres()` ?

E.g. the `etldoc` for zoom 7 is `osm_transportation_merge_linestring_gen4  ->  layer_transportation:z7` thus the `_gen4` matview could be created as:

```sql
CREATE MATERIALIZED VIEW osm_transportation_merge_linestring_gen4 AS (
  SELECT ST_Simplify(geometry, zres(7)) AS geometry, [...]
  WHERE [...] AND ST_Length(geometry) > zres(7)
);
```

I also noticed `imposm3` uses `ST_SimplifyPreserveTopology()` for `generalized_tables` whereas `openmaptiles` uses `ST_Simplify()`.

**Comment by TomPohys** [comment]
Hi @brncsk, the usage of `ST_Simplify` insted of `ST_SimplifyPreserveTopology` is because of time. For 2 000 000 rows `ST_Simplify` took 900 ms, but for `ST_SimplifyPreserveTopology` it took  23 000 ms. 

Using `zres()` function is much more reliable, that is true. There is also old discussion about it https://github.com/openmaptiles/openmaptiles/pull/214. The tolerance values are now set up empirical through experiments (zres(10) for pixel_scale 256 is ca. 152). So for `osm_transportation_merge_linestring_gen4` will be `zres` more `zres(9)`(305) or `zres(10)` (150) then `zres(7)` (1222) even for zoom level 7.

**Comment by brncsk** [comment]
@TomPohys Thanks for the clarification!
